### ISSUE TITLE
[Bug]: Resource --> github app --> Docker Compose --> Build section: it doesn't save the location

### ISSUE THREAD

**Issue by guillempuche** [coollabsio/coolify#4348] opened 2024-11-20 22:15 UTC
### Error Message and Logs

If you try to edit **Build** --> **Docker Compose Location** filename, it doesn't work.

![Image](https://github.com/user-attachments/assets/832563a2-f6bf-4aeb-b9f0-f6ef3de76cc5)

### Steps to Reproduce

1. Create a Resource with Github App
2. In Build Pack,	select `Docker Compose`
3. In Build section --> Docker Compose Location, change the default `docker-compose.yaml` for `docker-compose.yml`
4. Save
5. It isn't save as `yml`, but `yaml`.

### Coolify Version

v4.0.0-beta.367

### Are you using Coolify Cloud?

Yes (Coolify Cloud)

**Comment by peaklabs-dev** [comment] 2024-11-26 14:05
I am not able to reproduce this issue, not with your public repo, nor with a GitHub app and a private report with the exact same file structure. Are you sure you set the exact path and use a valid GitHub app?

**Comment by peaklabs-dev** [comment] 2024-12-06 13:24
This is also fixed with the fix Andras made for the other issues, right?

**Comment by guillempuche** [comment] 2024-12-06 13:34
Right, Peak

**Closed** 2024-12-13 09:24 UTC
Labels: 🐞 Confirmed Bug
