### ISSUE TITLE
[Bug]: Twenty service is broken

### ISSUE THREAD

**Issue by scflode** [coollabsio/coolify#2451] opened 2024-06-11 12:02 UTC
### Description

The env var `SERVICE_FQDN_TWENTY` always seems to have a trailing slash which leads to a `404` when having deployed the service stack.

### Minimal Reproduction (if possible, example repository)

Create a Twenty service with some domain and open the dev tools. The GraphQL reference returns a `404`. See also (parts of) https://discord.com/channels/459365938081431553/1240717873920344154

### Version

v4.0.0-beta.294

**Comment by grogou** [comment] 2024-06-13 15:20
same for me, the problem is `/`

**Comment by Flowko** [comment] 2024-06-18 23:04
for a quick dirty solution, hit `edit compose file` and change these values `SERVER_URL` and `FRONT_BASE_URL` to your domain, instead of whtaever value it has:
```
- 'SERVER_URL=https://twenty.website.com'
- 'FRONT_BASE_URL=https://twenty.website.com'
```

**Comment by tanyudii** [comment] 2024-08-01 04:43
please 

> for a quick dirty solution, hit `edit compose file` and change these values `SERVER_URL` and `FRONT_BASE_URL` to your domain, instead of whtaever value it has:
> 
> ```
> - 'SERVER_URL=https://twenty.website.com'
> - 'FRONT_BASE_URL=https://twenty.website.com'
> ```

I have trying change `SERVER_URL` and `FRONT_BASE_URL` still not working. But I've add expose port inside twenty service and its working now.

**Comment by AltanS** [comment] 2024-08-14 09:03
Ok, so for me the fix was as well to set a `PORT` environment var on the twenty app container and then expose the port. On top of the `SERVER_URL` and `FRONT_BASE_URL` adjustments. 

``` YAML
services:
  twenty:
    image: 'twentycrm/twenty:latest'
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - 'FRONT_BASE_URL=https://twenty.example.com'
      - 'SERVER_URL=https://twenty.example.com'
      # rest of file 
```

**Comment by nooruddin-rahmani** [comment] 2024-10-08 23:04
Hello everyone hope you're doing great.
I am new to deploying apps and do not know the basics well.
I tried to deploy Twenty in Coolify from GitHub repo. After deploying, When I want to access Twenty, I get Bad Gateway any idea how it happens.
However when I want to deploy the pre-built one that Coolify provides it runs fine.

**Comment by peaklabs-dev** [comment] 2024-10-24 19:44
This issue has been fixed in the latest version and you can now deploy twenty CRM from the one click templates.

**Closed by peaklabs-dev** 2024-10-24 19:44 UTC
Labels: 🐛 Bug
