### ISSUE TITLE
[Bug]: Gitea Web UI is not accessible

### ISSUE THREAD

**Issue by dibu28** [coollabsio/coolify#985] opened 2023-03-11 12:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When I deploy Gitea Service I can not access it by the default port 3000 as it used by coolify or not exposed.

When I try to deploy it on my server or on the Demo Server of coolify

On my domain and Cloudflare I've tried to configure it with both https and http and got no luck.

Is it possible to expose or change default port of Gitea web?

This error appears in logs:
2023-03-11T12:42:29.110917556Z 2023/03/11 12:42:29 ...s/graceful/server.go:62:NewServer() [I] [640c7735-2] Starting new Web server: tcp:0.0.0.0:3000 on PID: 17
2023-03-11T12:42:48.577297579Z kex_exchange_identification: client sent invalid protocol identifier "GET / HTTP/1.1"
2023-03-11T12:42:48.577365606Z banner exchange: Connection from 172.18.112.2 port 59984: invalid format

### Steps To Reproduce

1 Go to coolify
2 deploy Gitea
3 try to open Gitea web UI

### Version

3.12.27

**Comment by magasb1** [comment] 2023-03-12 21:25
Related to #961. I believe this is because traefik doesnt connect to the correct port - the log shows that traefik is accessing the internal ssh port of gitea.

**Comment by tolstenko** [comment] 2023-03-15 00:39
I reverted to v3.12.17 and it worked for me. So probably something between those versions crashed gitea installation. 

Btw, gitea is not exposing ssh port correctly, should I report it here or in the [other repo](https://github.com/coollabsio/coolify-community-templates)? It looks like here it is related to this specific issue, so I didn't open a new issue.

**Comment by andrasbacsai** [comment] 2023-03-20 11:23
I got it fixed. Will be added to the next version.

**Comment by JamesTryand** [comment] 2024-05-15 00:00
This is still an issue : 
## Steps To Reproduce
* Create a new service
* Choose any of the Gitea installations
* (Complete the FQDN - this step is optional since it doesn't work even if the FQDN is specified)
* Deploy

**Comment by bdnugget** [comment] 2024-09-06 22:07
Thank you so much @harish2704 , this fixed it for me too!

**Comment by harish2704** [comment] 2024-09-12 03:52
@peaklabs-dev : Can't we fix this issue by adding above mentioned label in all required templates ?
If yes and that is the proffered solution, I can raise a PR for this bug fix.

Or if you are trying to automate this by deriving *port number* from `SERVICE_FQDN_*` variables, then it will be better to get fixed by  members of coolify team

**Comment by harish2704** [comment] 2024-09-28 19:30
Update: this bug does not exists  now ( using  [v4.0.0-beta.347](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.347) )

**Closed** 2024-09-30 20:20 UTC
