### ISSUE TITLE
[Bug]: Heroku buildpack not working

### ISSUE THREAD

**Issue by wallaceosmar** [coollabsio/coolify#689] opened 2022-10-20 06:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Fail after 2s.
```
[03:38:30.421] GitHub importer started.
[03:38:30.424] Cloning heroku/python-getting-started:main branch.
[03:38:30.723] Configuration changed.
[03:38:30.750] Building image started.
```

### Steps To Reproduce

1. create new app
2. add any heroku example in the git (https://github.com/heroku/python-getting-started)
3. enable debug log
4. deploy

### Version

3.10.16

**Comment by wallaceosmar** [comment] 2022-10-21 03:27
To deploy the container I had to force coolify to v3.10.1, I didn't test the exact version it stopped working

**Comment by andrasbacsai** [comment] 2022-10-23 09:49
I can reproduce it and will fix it in the next version.

**Comment by wallaceosmar** [comment] 2022-11-08 12:20
@andrasbacsai Ainda não funciona

**Comment by andrasbacsai** [comment] 2022-11-08 13:50
I tested it out and it works for me, or at least the build is working. But the application states an error, but that is just a python env configuration I thinks:

![image](https://user-images.githubusercontent.com/5845193/200581909-6331a16c-15a8-4160-a803-0c70303ad301.png)

**Comment by wallaceosmar** [comment] 2022-11-08 14:37
Tested in a new vm in DigitalOcean.

In my server one of the attempts of running show this log
```
[14:04:49.044] /usr/local/bin/pack: 1: Syntax error: redirection unexpected
[14:04:50.064] 2
```

**Comment by andrasbacsai** [comment] 2022-11-15 20:16
Strange, I cannot reproduce it. Can you show me a screenshot of the configuration for this application?

**Comment by wallaceosmar** [comment] 2022-11-17 23:06
@andrasbacsai after some digging in the source code i discover the pack script is not present in the image and the url to download the pack return a 404

RUN curl -SL https://cdn.coollabs.io/bin/linux/amd64/pack-v0.27.0 -o /usr/local/bin/pack
https://github.com/coollabsio/coolify/actions/runs/3479738443/jobs/5818653611#step:8:869

Work around

ssh in the vm
to get the container id use 
`sudo docker ps | grep  coollabsio/coolify:`
ssh in the coolify container with
`sudo docker exec -it 50d9dc89ae36 bash`
run
`(curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.27.0/pack-v0.27.0-linux.tgz" | tar -C /usr/local/bin/ --no-same-owner -xzv pack)`

**Comment by axlroden** [comment] 2022-11-18 10:51
Yea clean your docker cache, and you would be able to recreate the problem.

**Comment by kolosek** [comment] 2022-11-23 06:56
@wallaceosmar Thanks! It worked.

**Comment by wanglong167** [comment] 2022-12-26 08:44
@andrasbacsai   3.12.4

https://github.com/wanglong167/7777

![image](https://user-images.githubusercontent.com/456516/209526848-bbbfbce3-bbf8-42be-92bd-9093d0f8a3a0.png)

**Comment by andrasbacsai** [comment] 2023-09-08 08:57
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.

**Closed by andrasbacsai** 2023-09-08 08:57 UTC
