### ISSUE TITLE
[Bug]: PullHelperImageJob rate limit issue using Self Hosted coolify

### ISSUE THREAD

**Issue by MatteoGauthier** [coollabsio/coolify#3759] opened 2024-10-07 05:45 UTC
### Error Message and Logs

![Screenshot_20241007_051921_Discord](https://github.com/user-attachments/assets/f52829ff-a186-4bda-a448-6330701a422b)

```
PullHelperImageJob failed with: Error response from daemon: toomanyrequests: retry-after: 1.2362ms, allowed: 44000/minute
```

### Steps to Reproduce

1.
2.
3.
4.

### Coolify Version

v4.0.0-beta.355

### Are you using Coolify Cloud?

No (self-hosted)

### Additional Information

Ubuntu 22

**Comment by peaklabs-dev** [comment] 2024-10-07 06:16
This issue appears to be a duplicate of #3395. Please move to that issue for updates and discussions.

**Closed** 2024-10-07 06:17 UTC
Labels: 🐛 Bug, 🔍 Triage
