### ISSUE TITLE
[Bug]: Supabase db expose port

### ISSUE THREAD

**Issue by apertureless** [coollabsio/coolify#2052] opened 2024-04-23 09:47 UTC
### Description

I have deployed the supabase application, mostly with default settings.
In order to push db migrations from the location supabase instance, I need to specify the `--db-url`  

```bash
supabase db push --db-url="postgres://postgre[...]
```

In order for this to work, I have to expose the db port in coolify.

In the DB container I have set a public port and checked the checkbox "Make it publicly available".
But the port is not exposed.  Also if I set a name for the container, it keeps the old <id>

### Minimal Reproduction (if possible, example repository)

1. Create supabase application
2. Go to Settings in DB container
3. Set public port
4. "Set Make it publicly available"

### Exception or Error

Port not exposed

### Version

v4.0.0-beta.265

**Comment by Markus-Ende** [comment] 2024-04-24 10:14
Just found, that I can create destinations via Servers -> Destinations. But it is un-intuitive to not have this possibility from the side nav.

**Comment by Geczy** [comment] 2024-04-28 16:51
you can update the service compose yaml to expose the port

**Comment by boyhax** [comment] 2024-05-05 17:22
> you can update the service compose yaml to expose the port

i have same issue . i tried to add ports in compose file but the coolify version dont have it .so the coolify parsing of the file is ignoring ports by default.

no other solutions?

**Comment by Geczy** [comment] 2024-05-05 22:34
make a new project and copy the docker compose yaml for supabase and add the ports

**Comment by zilahir** [comment] 2024-05-06 19:27
> > you can update the service compose yaml to expose the port
> 
> i have same issue . i tried to add ports in compose file but the coolify version dont have it .so the coolify parsing of the file is ignoring ports by default.
> 
> no other solutions?

i've managed to get it work that way: 

```
    ports:
      - '5432:5432'
```

on the `supabase-db` service.

**Comment by CarefulGuru** [comment] 2024-05-22 22:50
Having the same issue with the MongoDB service - checking the "publicly available" box doesn't open it on the specified port

**Comment by Ryan-andpro-digital** [comment] 2024-06-07 11:02
I think once you select 'Make it publicly available' it creates an nginx docker container that does the forwarding (@andrasbacsai  correct me if I'm wrong :) ) - however, mine is stuck in a restarting loop (may or may not be the same sort of issue).

Before enabling
![CleanShot 2024-06-07 at 12 00 49](https://github.com/coollabsio/coolify/assets/160427283/ab293f99-f17f-4090-972c-21bbd6b20d54)

After enabling
![CleanShot 2024-06-07 at 12 01 42](https://github.com/coollabsio/coolify/assets/160427283/279a0378-9c7e-4d65-ade3-0a9d4b8807b5)

logs error:
```
2024/06/07 11:01:58 [emerg] 1#1: invalid port in upstream "m0s8w4s:" in /etc/nginx/nginx.conf:12
nginx: [emerg] invalid port in upstream "m0s8w4s:" in /etc/nginx/nginx.conf:12
```

**Comment by yaberkane05** [comment] 2024-06-15 13:56
having the same problem here.

> > you can update the service compose yaml to expose the port
> 
> Yeah, but I would assume the UI checkbox would do the same.

I unchecked the make public box to avoid port conflict, then did this. it worked !

**Comment by VonderVuflya** [comment] 2024-10-04 14:21
duplicate #3297

**Comment by Tihomir971** [comment] 2024-10-18 13:48
@andrasbacsai Is there solution for this? It prevents me from using Coolify for supabase and I wish i could standardize my infrastructure. I'm using separate Caddy server only for Supabase :(

**Comment by Tihomir971** [comment] 2024-10-18 13:48
@andrasbacsai Is there solution for this? It prevents me from using Coolify for supabase and I wish i could standardize my infrastructure. I'm using seaparate Caddy server only for Supabase :(

**Comment by peaklabs-dev** [comment] 2024-10-18 19:53
Duplicate of #3297. Please move to that issue for updates and discussions.

**Comment by peaklabs-dev** [comment] 2024-10-18 19:54
Duplicate of #3297. Please move to that issue for updates and discussions.

**Closed by peaklabs-dev** 2024-10-18 19:54 UTC
