### ISSUE TITLE
[Bug]: Containers don't get removed when we delete GlitchTip Service

### ISSUE THREAD

**Issue by zek** [coollabsio/coolify#855] opened 2023-01-16 10:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

Containers don't get removed when we delete GlitchTip Service

### Steps To Reproduce

1. Create GlitchTip service
2. Remove it
3. Check running containers `docker ps`

### Version

3.12.10

**Comment by grstreten** [comment] 2023-03-16 12:47
+1 on this issue, same steps to reproduce on 3.12.27

**Comment by andrasbacsai** [comment] 2023-09-08 09:08
I think this is fixed.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.

**Closed by andrasbacsai** 2023-09-08 09:09 UTC
