### ISSUE TITLE
[Bug]: formbricks: ❌ Invalid environment variables: { CRON_SECRET: [ 'Required' ] }

### ISSUE THREAD

**Issue by luckydonald** [coollabsio/coolify#3915] opened 2024-10-14 22:57 UTC
### Error Message and Logs

```
2024-10-14T20:32:26.130230186Z ❌ Invalid environment variables: { CRON_SECRET: [ 'Required' ] }
2024-10-14T20:32:26.136100593Z  ⨯ Error: Invalid environment variables
2024-10-14T20:32:26.136116517Z     at p (/home/nextjs/apps/web/.next/server/chunks/3517.js:1:880)
2024-10-14T20:32:26.136119481Z     at /home/nextjs/apps/web/.next/server/chunks/3517.js:1:1060
2024-10-14T20:32:26.136121804Z     at i (/home/nextjs/apps/web/.next/server/chunks/3517.js:1:1368)
2024-10-14T20:32:26.136123937Z     at 58758 (/home/nextjs/apps/web/.next/server/chunks/619.js:1:4366)
2024-10-14T20:32:26.136126100Z     at t (/home/nextjs/apps/web/.next/server/webpack-runtime.js:1:143)
2024-10-14T20:32:26.136128343Z     at 60972 (/home/nextjs/apps/web/.next/server/chunks/619.js:1:1235)
2024-10-14T20:32:26.136130467Z     at t (/home/nextjs/apps/web/.next/server/webpack-runtime.js:1:143)
2024-10-14T20:32:26.136132680Z     at 28003 (/home/nextjs/apps/web/.next/server/chunks/8003.js:1:1233)
2024-10-14T20:32:26.136134864Z     at t (/home/nextjs/apps/web/.next/server/webpack-runtime.js:1:143)
2024-10-14T20:32:26.136136996Z     at 86533 (/home/nextjs/apps/web/.next/server/app/page.js:1:11105)
```

### Steps to Reproduce

1. Hit "Pull image and redeploy" on formbricks
2. ???
3. it never starts

### Example Repository URL

https://github.com/coollabsio/coolify

### Coolify Version

v4.0.0-beta.323 and v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

NAME="Ubuntu" VERSION="20.04.6 LTS (Focal Fossa)" ID=ubuntu ID_LIKE=debian PRETTY_NAME="Ubuntu 20.04.6 LTS" VERSION_ID="20.04" HOME_URL="https://www.ubuntu.com/" SUPPORT_URL="https://help.ubuntu.com/" BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy" VERSION_CODENAME=focal UBUNTU_CODENAME=focal

### Additional Information

Probably using `:latest` is not the best way to handle this - as updates might break things - like shown.

**Comment by peaklabs-dev** [comment] 2024-10-28 17:16
I just tried to reproduce this with the Formbricks one click service and it seems to work fine. How are you deploying Formbricks?

**Comment by luckydonald** [comment] 2024-11-12 04:07
I used the template provided, and did something recently which updated the images.
In that case will a coolify update adapt the docker compose template as needed?

**Comment by peaklabs-dev** [comment] 2024-11-14 14:06
You could submit a PR if you change something to make it work and we will check it. And if you mean upgrading to a new version, you should do it yourself using docker image tags. Since it works for me, I will close this topic.

**Closed by peaklabs-dev** 2024-11-14 14:06 UTC
Labels: 🐛 Bug

**Comment by lakunle** [comment] 2024-11-16 14:45
Are there steps to resolving this bug? Still stuck trying to deploy formbricks using Unraid
