### ISSUE TITLE
[Bug]: Project removed without child services. 

### ISSUE THREAD

**Issue by ScriptNewbie** [coollabsio/coolify#3931] opened 2024-10-16 19:46 UTC
### Error Message and Logs

I deployed authentik with Coolify Cloud ("one click deployment"). Something went wrong - service was inaccessible. I removed the project. Project was removed, but resource / services were not. Initially I saw resource on resources tab, but then it disappeared. Right now I don't see the resource on resources tab, but containers related to the resource are still running. 

### Steps to Reproduce

1. Create a project
2. Deploy authentik in production environment
3. Remove the project (on /project/{project_id} route)
4.Project is removed, but without childs

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

Yes (Coolify Cloud)

**Comment by KaelWD** [comment] 2024-10-17 03:54
https://github.com/coollabsio/coolify/issues/3747?

**Comment by peaklabs-dev** [comment] 2024-10-17 09:01
Duplicate of #3747

**Closed by peaklabs-dev** 2024-10-17 09:01 UTC
Labels: 🐛 Bug, 🔍 Triage
