### ISSUE TITLE
[Bug]: logout causes infinity alert loop "This page has expired. Would you like to refresh the page?"

### ISSUE THREAD

**Issue by louisjrdev** [coollabsio/coolify#4051] opened 2024-10-28 18:40 UTC
### Error Message and Logs

Copy of #2291

I am running into this on 4.0.0-beta.360. Not sure what changed ( i have auto update on ), I went to log into my server after a little while and I keep facing the loop as described in the original issue.

### Steps to Reproduce

1.
2.
3.
4.

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by peaklabs-dev** [comment] 2024-10-28 18:43
Duplicate of #2291

**Closed by peaklabs-dev** 2024-10-28 18:43 UTC
Labels: 🐛 Bug, 🔍 Triage
