### ISSUE TITLE
Volumes are not cleaned up

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify#2729] opened 2024-06-30 19:43 UTC
* Create a docker compose app via private github.
* Delete it
* Check if volume is still exists

**Comment by ingokpp** [comment] 2024-06-30 19:59
I created an empty repo (private) with the [following compose file](https://github.com/coollabsio/coolify/blob/main/templates/compose/listmonk.yaml). After deploying, i ran `docker volume ls` which includes "listmonk-data". After deleting the resource the volume still remains.

**Comment by sukhcha-in** [comment] 2024-06-30 22:18
I am using docker compose, unused images and networks are not being cleaned as well.

**Comment by ayntk-ai** [comment] 2024-07-02 20:04
Same for networks: https://github.com/coollabsio/coolify/issues/2546

**Comment by ingokpp** [comment] 2024-07-05 09:11
Any news on this?

**Comment by Djemai-Samy** [comment] 2024-07-05 16:59
Same for preview deployments. They are deleted from the Coolify dashboard, but the containers are still running on the server.

**Comment by jSchenkel** [comment] 2024-07-09 02:42
Hello! I'm currently developing an AI tool that investigates issues, and I used this issue as a test to see if it could help. Below are the findings, which I hope might assist in resolving this issue faster.

**Boosterbot.ai Findings**

The root cause of the bug is the absence of explicit error handling and logging in the volume cleanup process. While the `deleting` event in the `Application` model attempts to remove Docker volumes, there is no confirmation of success or failure, leading to potential leftover volumes. Additionally, other related classes and methods do not include volume cleanup commands, contributing to the issue.
1. Identify the code responsible for handling the deletion of Docker Compose applications.
The `DeleteService` class in `app/Actions/Service/DeleteService.php` is responsible for handling the deletion of services, including Docker Compose applications. The `handle` method includes logic for deleting environment variables, applications, databases, and scheduled tasks associated with the service. It also constructs Docker CLI commands to remove volumes using `docker volume rm -f $storage->name` and executes them using `instant_remote_process`. However, there is no explicit check to ensure these commands are executed successfully.
2. Verify if there are any steps or commands in the identified code that handle the cleanup of Docker volumes.
The `StopApplication` class in `app/Actions/Application/StopApplication.php` and `StopApplicationOneServer.php` handle stopping applications but do not include commands to remove Docker volumes. The `DeleteResourceJob` class in `app/Jobs/DeleteResourceJob.php` calls `StopApplication::run`, `StopDatabase::run`, and `DeleteService::run`, but none of these actions explicitly handle Docker volume cleanup. The `delete_configurations` method in the `Service` model (`app/Models/Service.php`) removes the working directory but does not handle Docker volumes.
3. Check if the volume cleanup steps or commands are being executed correctly.
The `deleting` event in the `Application` model (`app/Models/Application.php`) includes logic to remove Docker volumes using `docker volume rm -f $storage->name` via `instant_remote_process`. However, there is no explicit error handling or logging to confirm the success of these commands. The `StopDatabase` class in `app/Actions/Database/StopDatabase.php` stops database containers but does not handle volume cleanup. The `CleanupStuckedResources` command in `app/Console/Commands/CleanupStuckedResources.php` does not address Docker volume cleanup.

These suggestions are automatically generated based on the context of the issue description and repository code. I'm actively looking for feedback to improve the tool's accuracy and relevance, so any insights you might have are greatly appreciated!

**Closed** 2024-07-11 11:01 UTC
Labels: 🐞 Bug, 👨‍🏭 Next
