### ISSUE TITLE
[Bug]: Domain Name & Remote Destination

### ISSUE THREAD

**Issue by ilikewebsite** [coollabsio/coolify#691] opened 2022-10-20 21:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I added remote destination, After it I have installed a  application which done perfectly also I added domain name and pointed domain name where coolify is installed but even after build success it's not wokring. Looks like some kind of DNS related issue.

### Steps To Reproduce

I added remote destination, After it I have installed a  application which done perfectly also I added domain name and pointed domain name where coolify is installed but even after build success it's not wokring. Looks like some kind of DNS related issue.

### Version

3.10.16

**Comment by ilikewebsite** [comment] 2022-11-10 08:26
What's the status ?

**Comment by rafalohaki** [comment] 2022-11-11 19:51
had no problem before

when trying to expose port
![image](https://user-images.githubusercontent.com/20607107/201421272-08cdedf2-bd6c-4e3e-be2b-348c8cda1ff1.png)

**Comment by andrasbacsai** [comment] 2022-11-15 20:13
> had no problem before
> 
> when trying to expose port ![image](https://user-images.githubusercontent.com/20607107/201421272-08cdedf2-bd6c-4e3e-be2b-348c8cda1ff1.png)

This has been fixed in the previous version.

I’ve tested deploying applications to remote destinations, but it works for me, so I cannot reproduce it.

Could you please check if your DNS settings in your domain provider are set correctly? The domain you want to use should point to the remote destination server, not the one where Coolify is installed.

If it persists, please reopen this issue.

**Closed by andrasbacsai** 2022-11-15 20:13 UTC
