### ISSUE TITLE
[Bug]: coolify container : bind() to 0.0.0.0:80 failed

### ISSUE THREAD

**Issue by thschersch** [coollabsio/coolify#4612] opened 2024-12-17 21:35 UTC
### Error Message and Logs

After upgrading an older installation (max 1 month) to 4.0.0-beta.379 the coolify container is unhealthy and logs 
````
2024/12/17 21:06:01 [emerg] 9961#9961: bind() to 0.0.0.0:80 failed (13: Permission denied)
 nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
````

the proxy is working, i can connect to the services and sites

### Steps to Reproduce

1. update coolify from ui
2. the ui is not working
3. the coolify container is unhealthy
4. updating coolify from cli does not fix the problem

### Coolify Version

v4.00-beta.379

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

ubuntu 22.04

### Additional Information

before updating coolify i had made an update / upgrade from ubuntu and unluckily i did not check if coolify is still running.
i tried to update coolify manually but it did not fix the problem.

**Comment by thschersch** [comment] 2024-12-17 21:47
the solution is already there

**Comment by peaklabs-dev** [comment] 2024-12-17 22:20
Duplicate of https://github.com/coollabsio/coolify/issues/4601

**Closed by peaklabs-dev** 2024-12-17 22:20 UTC
Labels: 🐛 Bug, 🔍 Triage
