### ISSUE TITLE
[Bug]: Multiplexed SSH connections fail for servers using Cloudflare Tunnels.

### ISSUE THREAD

**Issue by Paarth-K** [coollabsio/coolify#3382] opened 2024-09-10 17:43 UTC
### Description

Upgrading to v4.0.0-beta.332 with the multiplexed SSH connection causes servers using Cloudflare tunnels to be unreachable. 

### Minimal Reproduction (if possible, example repository)

Upgrade to v4.0.0-beta.332 and use a server connected with Cloudflare tunnels. 

(to fix downgrade to v4.0.0-beta.325)

### Exception or Error

<img width="1440" alt="SCR-20240910-stfl-3" src="https://github.com/user-attachments/assets/639949db-6172-4aa4-965b-4910cebaa7b0">
<img width="1440" alt="SCR-20240910-ssrg" src="https://github.com/user-attachments/assets/67b21be1-4c9c-4955-b5fc-31a25562606f">

### Version

v4.0.0-beta.332

### Cloud?

- [ ] Yes
- [X] No

**Comment by peaklabs-dev** [comment] 2024-09-10 20:36
@Paarth-K  I tried it and whether my fix is there or not it works. Just validate the server and then use the automated cloudflare tunnel setup. Did you manually configure cloudfalre tunnels as I cannot reproduce this. 
1. Validate the server
2. Configure cloudflare tunnel
<img width="635" alt="image" src="https://github.com/user-attachments/assets/44aa340c-05a9-415a-82c2-cb5cfb8a480b">

3. Do the automatic configuration
-> What did you do differently?

**Comment by peaklabs-dev** [comment] 2024-09-11 21:54
@Jalx please make a new issue as this issue is not related to the cf tunnel one.

**Comment by andrasbacsai** [comment] 2024-09-12 10:39
This will be fixed in the upcoming version.

**Closed** 2024-09-12 10:43 UTC
Labels: 🐞 Bug, 🦟 Confirmed Bug
