### ISSUE TITLE
[Bug]: Pocketbase is experiencing issues.

### ISSUE THREAD

**Issue by fabioallexandr3** [coollabsio/coolify#2951] opened 2024-07-26 10:30 UTC
### Description

nstallation completed without any intervention in the files, just clicking and proceeding to the next step.

Both in the Cloud and self-hosted.

### Minimal Reproduction (if possible, example repository)

https://github.com/user-attachments/assets/5705b5bc-07d1-44f4-b749-4dab10686ae1

### Exception or Error

2024-07-26T10:17:53.508808986Z 2024/07/26 10:17:53 Server started at http://0.0.0.0:8080
2024-07-26T10:17:53.509060864Z ├─ REST API: http://0.0.0.0:8080/api/
2024-07-26T10:17:53.509072186Z └─ Admin UI: http://0.0.0.0:8080/_/

### Version

4.0.0-Beta.3.18

### Cloud?

- [ ] Yes
- [X] No

**Comment by ItsTarikBTW** [comment] 2024-07-27 11:40
u should go to http://YOUR_URL/_/
to access the admin UI

**Comment by maietta** [comment] 2024-07-27 14:00
This is certainly not a bug and @ItsTarikBTW is correct, you're access is at /_/ for the admin panel.

In my case, I assigned to the same domain as my website with /api/, so I must append the URL to look like. /api/_/.

Pocketbase has no endpoint defined for /, which is why you are seeing the 404.

**Closed** 2024-07-28 08:31 UTC
