### ISSUE TITLE
[Bug]: Multiple cleanup queues

### ISSUE THREAD

**Issue by ari-party** [coollabsio/coolify#4489] opened 2024-12-06 02:00 UTC
### Error Message and Logs

![Image](https://github.com/user-attachments/assets/51edea4e-24a2-436f-8521-352bb4c19e07)

### Steps to Reproduce

I really am not sure.
This is likely an edge case of something.

### Coolify Version

v4.0.0-beta.375

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by peaklabs-dev** [comment] 2024-12-13 09:12
I am unable to reproduce it, it is definitely a rare edge case. If you have this problem again and know how to reproduce it, please let me know. I will close this as we have added some fixes in the next version so it may be resolved.

**Closed by peaklabs-dev** 2024-12-13 09:12 UTC
Labels: 🐛 Bug, 🔍 Triage
