### ISSUE TITLE
Application with multiple domains 

### ISSUE THREAD

**Issue by danieldocki** [coollabsio/coolify#256] opened 2022-03-31 17:05 UTC
Possibility of supporting an application with multiple domains, for example:

mainapp.com
subdomain.mainapp.com
etc...

**Comment by koch-crsd** [comment] 2023-02-01 11:18
I think this is a duplicate of #96 .?

**Closed** 2023-09-08 08:42 UTC

**Comment by Geczy** [comment] 2023-11-30 06:12
you can do this with my pr at https://github.com/coollabsio/coolify/pull/1505
