### ISSUE TITLE
[Bug]: env vars don't work for docker-compose based Preview Deployments

### ISSUE THREAD

**Issue by ton77v** [coollabsio/coolify#2127] opened 2024-05-03 06:56 UTC
### Description

At least the "Build variable" ones, even though it works fine in normal deployments and I declare/consume them in docker-compose.yaml

Example:
```
services:
  something:
    build:
      context: .
      args:
        NPM_TOKEN: ${NPM_TOKEN:?NPM_TOKEN not set}
        # ...
    ports:
      - "3333:3000"
    environment:
      - NPM_TOKEN=${NPM_TOKEN:?NPM_TOKEN not set}
      # ...
```

Works as expected with regular deployments, however for Preview Deployments I'm getting the following error:
```
[2024-May-03 03:17:50.638004] error while interpolating services.something-pr-75.build.args.NPM_TOKEN: required variable NPM_TOKEN is missing a value: NPM_TOKEN not set
```

Switching the same resource to the Nixpacks build where nixpacks.toml relies on the same env variables solves the issue

### Minimal Reproduction (if possible, example repository)

1. Add a GitHub repo
2. Configure the repo-based resource choosing Docker Compose build pack
3. Add some environment variables and declare them in docker-compose
4. Add e.g. a custom build command to see the env vars: `printenv && docker compose build`
5. Enable Preview Deployments, create PR and push there.

See your env vars missing in the logs e.g. below

### Exception or Error

[COMMAND] docker exec XXXXXX bash -c 'cd /artifacts/XXXXXX && printenv && docker compose build'
[OUTPUT]
HOSTNAME=...
PWD=/artifacts/XXXXXX
HOME=/root
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
OLDPWD=/artifacts
_=/bin/printenv

### Version

v4.0.0-beta.271

**Comment by maurobender** [comment] 2024-05-08 15:54
I'm also seeing this issue on version `v4.0.0-beta.276`. Running the `env` command inside de container only shows variables defined in the docker-compose file but not those defined in the `Configuration > Environment Variables > Preview Deployments`.

**Comment by K4M1s** [comment] 2024-05-17 18:00
Same problem on version `v4.0.0-beta.283`

**Comment by ton77v** [comment] 2024-05-27 06:58
Any progress on this one? Now with another bug for Nixpacks https://github.com/coollabsio/coolify/issues/2292 one of my resources just won't work at all

**Comment by andrasbacsai** [comment] 2024-06-04 09:20
I have test with [this](https://github.com/coollabsio/coolify-examples/blob/main/docker-compose/docker-compose.yml) small example compose app and it works as designed.

![image](https://github.com/coollabsio/coolify/assets/5845193/e29a2ebe-e2ca-4e60-9bbc-567493a244bf)

The production deployments have the value of `test`:
![image](https://github.com/coollabsio/coolify/assets/5845193/d51811e4-d362-4bd3-8a7c-29a77abe493e)

Preview deployments have the value of `preview`:
![image](https://github.com/coollabsio/coolify/assets/5845193/034ae654-0aad-42f0-809c-997a06d1fbd1)

**Comment by andrasbacsai** [comment] 2024-06-04 09:29
I have made a few updates since that version, so I hope it will be fixed in the upcoming version.

**Closed** 2024-06-04 09:30 UTC
