### ISSUE TITLE
[Bug]: Unable to unlock after locking environment variable

### ISSUE THREAD

**Issue by JohnGeek-dev** [coollabsio/coolify#2697] opened 2024-06-26 10:35 UTC
### Description

In `v4.0.0-beta.297` (and possibly most recent version since I couldn't find any bug report on this), once an environment variable is locked, it cannot be unlocked, preventing any updates or changes to that variable even in `Developer view`.

PS: I've forgotten to test this when I upgraded to `v4.0.0-beta.306`, I've downgraded the version due to some issues when trying to deploy Supabase.

### Minimal Reproduction (if possible, example repository)

1. Lock an environment variable.
2. Attempt to unlock the environment variable to make changes.
3. Notice that the variable remains locked and is not modifiable even in `Developer view`. 

### Version

v4.0.0-beta.297

**Comment by LordSalmon** [comment] 2024-06-29 07:24
Same problem here but with directus. It is however not dependant on a service I assume, but rather on the environment handling 👍🏼 

Version: `v4.0.0-beta.306`

**Comment by kldzj** [comment] 2024-07-14 19:33
If you just need to reveal the locked secret values, you can simply run the `env` command inside your container, using the `Command` tab.

**Comment by LordSalmon** [comment] 2024-07-14 19:47
Nope I really want to change it. Imagine (not that it would have happened to me 🙃) you need to pass an FQDN into your service, you locked it and now the FQDN should change. I am not sure if it's expected behaviour to just delete the locked env record and create one with the same name. Or is it?

Maybe @andrasbacsai could give us an explanation what the philosophy of locked environment variables is since I didn't find anything in the docs.

**Comment by andrasbacsai** [comment] 2024-07-26 10:05
> Nope I really want to change it. Imagine (not that it would have happened to me 🙃) you need to pass an FQDN into your service, you locked it and now the FQDN should change. I am not sure if it's expected behaviour to just delete the locked env record and create one with the same name. Or is it?
> 
> Maybe @andrasbacsai could give us an explanation what the philosophy of locked environment variables is since I didn't find anything in the docs.

The locking mechanism should work like this. You lock, you could never unlock it. Only delete and create a new one.

The FQDN part (with `SERVICE_FQDN` and `SERVICE_URL` variables) will be fixed in the next version (I have made a bug 11 days ago that prevents to update these variables if you change the fqdn).

**Comment by peaklabs-dev** [comment] 2024-10-28 17:06
Since locking of environment variable is intended to work this way, I will close this issue.

**Closed by peaklabs-dev** 2024-10-28 17:06 UTC

**Comment by teknology** [comment] 2024-11-20 02:27
I wish i knew that before pressing the lock button. I thought it was some sort of security that needed an admin code. How is the current way it works beneficial?
