### ISSUE TITLE
[Bug]: column "image" of relation "service_applications" does not exist

### ISSUE THREAD

**Issue by raphaelbernhart** [coollabsio/coolify#3191] opened 2024-08-22 10:42 UTC
### Description

When I try to add a coolify-provided-service or an docker compose application, I get an error. The ressource gets created but I get an error screen and I cannot deploy it. => [image](https://github.com/user-attachments/assets/991bbed1-1b5b-4b17-ab29-e9fb570a3cae)

I found [this issue](https://github.com/coollabsio/coolify/issues/1265) but as it is old, I am not sure if this is still the way to do the migrations.

Output of `docker exec coolify bash -c "php artisan migrate:status"`:
```
  Migration name .............................................. Batch / Status  
  2014_10_12_000000_create_users_table ............................... [1] Ran  
  2014_10_12_100000_create_password_reset_tokens_table ............... [1] Ran  
  2014_10_12_200000_add_two_factor_columns_to_users_table ............ [1] Ran  
  2019_12_14_000001_create_personal_access_tokens_table .............. [1] Ran  
  2023_03_20_112410_create_activity_log_table ........................ [1] Ran  
  2023_03_20_112411_add_event_column_to_activity_log_table ........... [1] Ran  
  2023_03_20_112412_add_batch_uuid_column_to_activity_log_table ...... [1] Ran  
  2023_03_20_112809_create_sessions_table ............................ [1] Ran  
  2023_03_20_112811_create_teams_table ............................... [1] Ran  
  2023_03_20_112812_create_team_user_table ........................... [1] Ran  
  2023_03_20_112813_create_team_invitations_table .................... [1] Ran  
  2023_03_20_112814_create_instance_settings_table ................... [1] Ran  
  2023_03_24_140711_create_servers_table ............................. [1] Ran  
  2023_03_24_140712_create_server_settings_table ..................... [1] Ran  
  2023_03_24_140853_create_private_keys_table ........................ [1] Ran  
  2023_03_27_075351_create_projects_table ............................ [1] Ran  
  2023_03_27_075443_create_project_settings_table .................... [1] Ran  
  2023_03_27_075444_create_environments_table ........................ [1] Ran  
  2023_03_27_081716_create_applications_table ........................ [1] Ran  
  2023_03_27_081717_create_application_settings_table ................ [1] Ran  
  2023_03_27_081718_create_application_previews_table ................ [1] Ran  
  2023_03_27_083621_create_services_table ............................ [1] Ran  
  2023_03_27_085020_create_standalone_dockers_table .................. [1] Ran  
  2023_03_27_085022_create_swarm_dockers_table ....................... [1] Ran  
  2023_03_28_062150_create_kubernetes_table .......................... [1] Ran  
  2023_03_28_083723_create_github_apps_table ......................... [1] Ran  
  2023_03_28_083726_create_gitlab_apps_table ......................... [1] Ran  
  2023_04_03_111012_create_local_persistent_volumes_table ............ [1] Ran  
  2023_05_04_194548_create_environment_variables_table ............... [1] Ran  
  2023_05_17_104039_create_failed_jobs_table ......................... [1] Ran  
  2023_05_24_083426_create_application_deployment_queues_table ....... [1] Ran  
  2023_06_22_131459_move_wildcard_to_server .......................... [1] Ran  
  2023_06_23_084605_remove_wildcard_domain_from_instancesettings ..... [1] Ran  
  2023_06_23_110548_next_channel_updates ............................. [1] Ran  
  2023_06_23_114131_change_env_var_value_length ...................... [1] Ran  
  2023_06_23_114132_remove_default_redirect_from_instance_settings ... [1] Ran  
  2023_06_23_114133_use_application_deployment_queues_as_activity .... [1] Ran  
  2023_06_23_114134_add_disk_usage_percentage_to_servers ............. [1] Ran  
  2023_07_13_115117_create_subscriptions_table ....................... [1] Ran  
  2023_07_13_120719_create_webhooks_table ............................ [1] Ran  
  2023_07_13_120721_add_license_to_instance_settings ................. [1] Ran  
  2023_07_27_182013_smtp_discord_schemaless_to_normal ................ [1] Ran  
  2023_08_06_142951_add_description_field_to_applications_table ...... [1] Ran  
  2023_08_06_142952_remove_foreignId_environment_variables ........... [1] Ran  
  2023_08_06_142954_add_readonly_localpersistentvolumes .............. [1] Ran  
  2023_08_07_073651_create_s3_storages_table ......................... [1] Ran  
  2023_08_07_142950_create_standalone_postgresqls_table .............. [1] Ran  
  2023_08_08_150103_create_scheduled_database_backups_table .......... [1] Ran  
  2023_08_10_113306_create_scheduled_database_backup_executions_table  [1] Ran  
  2023_08_10_201311_add_backup_notifications_to_teams ................ [1] Ran  
  2023_08_11_190528_add_dockerfile_to_applications_table ............. [1] Ran  
  2023_08_15_095902_create_waitlists_table ........................... [1] Ran  
  2023_08_15_111125_update_users_table ............................... [1] Ran  
  2023_08_15_111126_update_servers_add_unreachable_count_table ....... [1] Ran  
  2023_08_22_071048_add_boarding_to_teams ............................ [2] Ran  
  2023_08_22_071049_update_webhooks_type ............................. [2] Ran  
  2023_08_22_071050_update_subscriptions_stripe ...................... [2] Ran  
  2023_08_22_071051_add_stripe_plan_to_subscriptions ................. [3] Ran  
  2023_08_22_071052_add_resend_as_email .............................. [3] Ran  
  2023_08_22_071053_add_resend_as_email_to_teams ..................... [3] Ran  
  2023_08_22_071054_add_stripe_reasons ............................... [4] Ran  
  2023_08_22_071055_add_discord_notifications_to_teams ............... [4] Ran  
  2023_08_22_071056_update_telegram_notifications .................... [5] Ran  
  2023_08_22_071057_add_nixpkgsarchive_to_applications ............... [6] Ran  
  2023_08_22_071058_add_nixpkgsarchive_to_applications_remove ........ [6] Ran  
  2023_08_22_071059_add_stripe_trial_ended ........................... [6] Ran  
  2023_08_22_071060_change_invitation_link_length .................... [7] Ran  
  2023_09_20_082541_update_services_table ............................ [9] Ran  
  2023_09_20_082733_create_service_databases_table ................... [9] Ran  
  2023_09_20_082737_create_service_applications_table ................ [9] Ran  
  2023_09_20_083549_update_environment_variables_table ............... [9] Ran  
  2023_09_22_185356_create_local_file_volumes_table .................. [9] Ran  
  2023_09_23_111808_update_servers_with_cloudflared .................. [9] Ran  
  2023_09_23_111809_remove_destination_from_services_table .......... [10] Ran  
  2023_09_23_111811_update_service_applications_table ............... [10] Ran  
  2023_09_23_111812_update_service_databases_table .................. [10] Ran  
  2023_09_23_111813_update_users_databases_table .................... [11] Ran  
  2023_09_23_111814_update_local_file_volumes_table ................. [12] Ran  
  2023_09_23_111815_add_healthcheck_disable_to_apps_table ........... [13] Ran  
  2023_09_23_111816_add_destination_to_services_table ............... [13] Ran  
  2023_09_23_111817_use_instance_email_settings_by_default .......... [13] Ran  
  2023_09_23_111818_set_notifications_on_by_default ................. [13] Ran  
  2023_09_23_111819_add_server_emails ............................... [13] Ran  
  2023_10_08_111819_add_server_unreachable_count .................... [13] Ran  
  2023_10_10_100320_update_s3_storages_table ........................ [13] Ran  
  2023_10_10_113144_add_dockerfile_location_applications_table ...... [13] Ran  
  2023_10_12_132430_create_standalone_redis_table ................... [13] Ran  
  2023_10_12_132431_add_standalone_redis_to_environment_variables_table  [13] Ran  
  2023_10_12_132432_add_database_selection_to_backups ............... [13] Ran  
  2023_10_18_072519_add_custom_labels_applications_table ............ [13] Ran  
  2023_10_19_101331_create_standalone_mongodbs_table ................ [13] Ran  
  2023_10_19_101332_add_standalone_mongodb_to_environment_variables_table  [13] Ran  
  2023_10_24_103548_create_standalone_mysqls_table .................. [14] Ran  
  2023_10_24_120523_create_standalone_mariadbs_table ................ [14] Ran  
  2023_10_24_120524_add_standalone_mysql_to_environment_variables_table  [14] Ran  
  2023_10_24_124934_add_is_shown_once_to_environment_variables_table  [14] Ran  
  2023_11_01_100437_add_restart_to_deployment_queue ................. [15] Ran  
  2023_11_07_123731_add_target_build_dockerfile ..................... [15] Ran  
  2023_11_08_112815_add_custom_config_standalone_postgresql ......... [15] Ran  
  2023_11_09_133332_add_public_port_to_service_databases ............ [15] Ran  
  2023_11_12_180605_change_fqdn_to_longer_field ..................... [15] Ran  
  2023_11_13_133059_add_sponsorship_disable ......................... [16] Ran  
  2023_11_14_103450_add_manual_webhook_secret ....................... [16] Ran  
  2023_11_14_121416_add_git_type .................................... [16] Ran  
  2023_11_16_101819_add_high_disk_usage_notification ................ [16] Ran  
  2023_11_16_220647_add_log_drains .................................. [16] Ran  
  2023_11_17_160437_add_drain_log_enable_by_service ................. [17] Ran  
  2023_11_20_094628_add_gpu_settings ................................ [17] Ran  
  2023_11_21_121920_add_additional_destinations_to_apps ............. [17] Ran  
  2023_11_24_080341_add_docker_compose_location ..................... [17] Ran  
  2023_11_28_143533_add_fields_to_swarm_dockers ..................... [17] Ran  
  2023_11_29_075937_change_swarm_properties ......................... [17] Ran  
  2023_12_01_091723_save_logs_view_settings ......................... [18] Ran  
  2023_12_01_095356_add_custom_fluentd_config_for_logdrains ......... [18] Ran  
  2023_12_08_162228_add_soft_delete_services ........................ [19] Ran  
  2023_12_11_103611_add_realtime_connection_problem ................. [19] Ran  
  2023_12_13_110214_add_soft_deletes ................................ [20] Ran  
  2023_12_17_155616_add_custom_docker_compose_start_command ......... [21] Ran  
  2023_12_18_093514_add_swarm_related_things ........................ [21] Ran  
  2023_12_19_124111_add_swarm_cluster_grouping ...................... [21] Ran  
  2023_12_30_134507_add_description_to_environments ................. [22] Ran  
  2023_12_31_173041_create_scheduled_tasks_table .................... [24] Ran  
  2024_01_01_231053_create_scheduled_task_executions_table .......... [24] Ran  
  2024_01_02_113855_add_raw_compose_deployment ...................... [23] Ran  
  2024_01_12_123422_update_cpuset_limits ............................ [24] Ran  
  2024_01_15_084609_add_custom_dns_server ........................... [25] Ran  
  2024_01_16_115005_add_build_server_enable ......................... [26] Ran  
  2024_01_21_130328_add_docker_network_to_services .................. [27] Ran  
  2024_01_23_095832_add_manual_webhook_secret_bitbucket ............. [29] Ran  
  2024_01_23_113129_create_shared_environment_variables_table ....... [28] Ran  
  2024_01_24_095449_add_concurrent_number_of_builds_per_server ...... [28] Ran  
  2024_01_25_073212_add_server_id_to_queues ......................... [28] Ran  
  2024_01_27_164724_add_application_name_and_deployment_url_to_queue  [29] Ran  
  2024_01_29_072322_change_env_variable_length ...................... [29] Ran  
  2024_01_29_145200_add_custom_docker_run_options ................... [30] Ran  
  2024_02_01_111228_create_tags_table ............................... [30] Ran  
  2024_02_05_105215_add_destination_to_app_deployments .............. [31] Ran  
  2024_02_06_132748_add_additional_destinations ..................... [32] Ran  
  2024_02_08_075523_add_post_deployment_to_applications ............. [37] Ran  
  2024_02_08_112304_add_dynamic_timeout_for_deployments ............. [32] Ran  
  2024_02_15_101921_add_consistent_application_container_name ....... [33] Ran  
  2024_02_15_192025_add_is_gzip_enabled_to_services ................. [33] Ran  
  2024_02_20_165045_add_permissions_to_github_app ................... [34] Ran  
  2024_02_22_090900_add_only_this_server_deployment ................. [34] Ran  
  2024_02_23_143119_add_custom_server_limits_to_teams_ultimate ...... [35] Ran  
  2024_02_25_222150_add_server_force_disabled_field ................. [35] Ran  
  2024_03_04_092244_add_gzip_enabled_and_stripprefix_settings ....... [36] Ran  
  2024_03_07_115054_add_notifications_notification_disable .......... [37] Ran  
  2024_03_08_180457_nullable_password ............................... [38] Ran  
  2024_03_11_150013_create_oauth_settings ........................... [38] Ran  
  2024_03_14_214402_add_multiline_envs .............................. [38] Ran  
  2024_03_18_101440_add_version_of_envs ............................. [38] Ran  
  2024_03_22_080914_remove_popup_notifications ...................... [38] Ran  
  2024_03_26_122110_remove_realtime_notifications ................... [38] Ran  
  2024_03_28_114620_add_watch_paths_to_apps ......................... [39] Ran  
  2024_04_09_095517_make_custom_docker_commands_longer .............. [40] Ran  
  2024_04_10_071920_create_standalone_keydbs_table .................. [41] Ran  
  2024_04_10_082220_create_standalone_dragonflies_table ............. [41] Ran  
  2024_04_10_091519_create_standalone_clickhouses_table ............. [41] Ran  
  2024_04_10_124015_add_permission_local_file_volumes ............... [41] Ran  
  2024_04_12_092337_add_config_hash_to_other_resources .............. [41] Ran  
  2024_04_15_094703_add_literal_variables ........................... [42] Ran  
  2024_04_16_083919_add_service_type_on_creation .................... [42] Ran  
  2024_04_17_132541_add_rollback_queues ............................. [42] Ran  
  2024_04_25_073615_add_docker_network_to_application_settings ...... [43] Ran  
  2024_04_29_111956_add_custom_hc_indicator_apps .................... [44] Ran  
  2024_05_06_093236_add_custom_name_to_application_settings ......... [45] Ran  
  2024_05_07_124019_add_server_metrics .............................. [46] Ran  
  2024_05_10_085215_make_stripe_comment_longer ...................... [47] Ran  
  2024_05_15_091757_add_commit_message_to_app_deployment_queue ...... [47] Ran  
  2024_05_15_151236_add_container_escape_toggle ..................... [47] Ran  
  2024_05_17_082012_add_env_sorting_toggle .......................... [48] Ran  
  2024_05_21_125739_add_scheduled_tasks_notification_to_teams ....... [49] Ran  
  2024_05_22_103942_change_pre_post_deployment_commands_length_in_applications  [50] Ran  
  2024_05_23_091713_add_gitea_webhook_to_applications ............... [50] Ran  
  2024_06_05_101019_add_docker_compose_pr_domains ................... [51] Ran  
  2024_06_06_103938_change_pr_issue_commend_id_type ................. [51] Ran  
  2024_06_11_081614_add_www_non_www_redirect ........................ [51] Ran  
  2024_06_18_105948_move_server_metrics ............................. [52] Ran  
  2024_06_20_102551_add_server_api_sentinel ......................... [52] Ran  
  2024_06_21_143358_add_api_deployment_type ......................... [52] Ran  
  2024_06_22_081140_alter_instance_settings_add_instance_name ....... [52] Ran  
  2024_06_25_184323_update_db ....................................... [53] Ran  
  2024_07_01_115528_add_is_api_allowed_and_iplist ................... [53] Ran  
  2024_07_05_120217_remove_unique_from_tag_names .................... [53] Ran  
  2024_07_11_083719_application_compose_versions .................... [54] Ran  
  2024_07_17_123828_add_is_container_labels_readonly ................ [55] Ran  
  2024_07_18_110424_create_application_settings_is_preserve_repository_enabled  [55] Ran  
  2024_07_18_123458_add_force_cleanup_server ........................ [55] Ran  
  2024_07_19_132617_disable_healtcheck_by_default ................... [56] Ran  
  2024_07_23_112710_add_validation_logs_to_servers .................. [56] Ran  
  2024_08_05_142659_add_update_frequency_settings ................... [57] Ran  
  2024_08_07_155324_add_proxy_label_chooser ......................... [57] Ran
```

So my questions would be:
What migrations are the ones causing the problem?
What command do I need to execute to run migrations?
(Best case) How can I solve it?

### Minimal Reproduction (if possible, example repository)

Not really possible to add minimal reproduction as this probably was caused by a development build.

### Exception or Error

```Error: SQLSTATE[42703]: Undefined column: 7 ERROR: column "image" of relation "service_applications" does not exist LINE 1: insert into "service_applications" ("name", "image", "servic... ^ (Connection: pgsql, SQL: insert into "service_applications" ("name", "image", "service_id", "uuid", "updated_at", "created_at") values (grafana, grafana/grafana-oss, 50, lc80cg0ckcgsg80kcggogcwg, 2024-08-22 10:42:12, 2024-08-22 10:42:12) returning "id")```

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by peaklabs-dev** [comment] 2024-09-27 16:47
I would honestly just reinstall coolify if you have the option. If not, you can run the following commands, but be aware that this **may break coolify's integrity and result in data loss**!

1. Rollback the migration
```bash
sudo docker exec -it coolify php artisan migrate:rollback --path=/database/migrations/2023_09_23_111811_update_service_applications_table.php
``` 
2. Run the migration that adds the image column again
```Bash
sudo docker exec -it coolify php artisan migrate --path=database/migrations/2023_09_23_111811_update_service_applications_table.php
```

**Comment by raphaelbernhart** [comment] 2024-10-14 07:22
> I would honestly just reinstall coolify if you have the option. If not, you can run the following commands, but be aware that this **may break coolify and it could/ will result in data loss if you have services**!
> 
> 1. Rollback the migration
> 
> ```shell
> sudo docker exec -it coolify php artisan migrate:rollback --path=/database/migrations/2023_09_23_111811_update_service_applications_table.php
> ```
> 
> 2. Run the migration that adds the image column again
> 
> ```shell
> sudo docker exec -it coolify php artisan migrate --path=database/migrations/2023_09_23_111811_update_service_applications_table.php
> ```
> 
> Please let me know if this helps.

Thanks for the reply! IMO the migration in this case is no option for me.

Is there a reinstall guide somewhere, I could not find any.
Atm the best option seems to be:
1. Setup a second server
2. Install coolify there
3. Move services over
Backing up the primary instance and restoring it on the second server is no option as the bug/problem then probably just gets carried over?
4. Remove primary server and set second server as new primary?

What do you think?

**Comment by peaklabs-dev** [comment] 2024-10-16 14:42
Yes. I would just set up a new server and manually migrate all the stuff over. I would not add the server to the current server as you would need a new Coolify server, not just a server for deployments. As this is not a bug rather a wired on case issue I am closing this.

**Closed by peaklabs-dev** 2024-10-16 14:42 UTC
