### ISSUE TITLE
[Bug]: Unable to create a directory at /var/www/html/storage/app/ssh/keys.

### ISSUE THREAD

**Issue by SarkarKurdish** [coollabsio/coolify#2410] opened 2024-06-09 17:58 UTC
### Description

I was migrating my websites and randomly got this error I can't open the dashboard at all even after restarting the server

![image](https://github.com/coollabsio/coolify/assets/37934074/c0d23d46-c23b-4af3-b633-e1a458fa23b0)

### Minimal Reproduction (if possible, example repository)

It was not anything particular 

### Exception or Error

500

Something is not okay, are you okay?
There has been an error, we are working on it.

Error: Unable to create a directory at /var/www/html/storage/app/ssh/keys. (View: /var/www/html/resources/views/livewire/server/proxy/status.blade.php) (View: /var/www/html/resources/views/livewire/server/proxy/status.blade.php) (View: /var/www/html/resources/views/livewire/server/proxy/status.blade.php)

### Version

v4.0.0-beta.294

**Comment by MrPrinceRawat** [comment] 2024-06-10 06:54
Have you checked the logs? Maybe it's a permission issue.

**Comment by SarkarKurdish** [comment] 2024-06-10 07:03
> Have you checked the logs? Maybe it's a permission issue.

The application was functioning normally for the first two days, however, an issue has since arisen. Even if it is a simple permissions issue, it is worth investigating the root cause as it is disrupting the entire Coolify workflow.

**Comment by braedencrankd** [comment] 2024-06-19 20:44
Iv'e had issues with permissions when running a Statamic project (laravel). My app doesn't have permissions to write to files, eg. cache files. Not sure if this is related, but sounds similar. As a work around I could run `chmod 777 ./filepath/filename` if the file already existed.

**Comment by PeraSite** [comment] 2024-06-20 16:29
I'm also getting this problem, after trying reinstall/downgrade Coolify.

The logs of coolify container is:
```
Brought to you by serversideup.net
--------------------------------------------------------------------

To support Server Side Up projects visit:
https://serversideup.net/sponsor
-------------------------------------
GID/UID
-------------------------------------

User uid:    9999
User gid:    9999
-------------------------------------

🏃‍♂️ Checking for Laravel automations...
🔐 Linking the storage...
🔓 SSL_MODE has been DISABLED, setting the web server to work in HTTP only...

   ERROR  The [public/storage] link already exists.


In Connection.php line 829:

  SQLSTATE[08006] [7] connection to server at "postgres" (172.18.0.3), port 5
  432 failed: FATAL:  password authentication failed for user "coolify" (Conn
  ection: pgsql, SQL: select * from information_schema.tables where table_cat
  alog = coolify and table_schema = public and table_name = migrations and ta
  ble_type = 'BASE TABLE')


In Connector.php line 65:

  SQLSTATE[08006] [7] connection to server at "postgres" (172.18.0.3), port 5
  432 failed: FATAL:  password authentication failed for user "coolify"


s6-rc: warning: unable to start service db-migration: command exited 1
[20-Jun-2024 16:26:42] NOTICE: fpm is running, pid 111
[20-Jun-2024 16:26:43] NOTICE: ready to handle connections
[20-Jun-2024 16:26:43] NOTICE: systemd monitor interval set to 10000ms
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
[20-Jun-2024 16:26:44] NOTICE: Terminating ...
[20-Jun-2024 16:26:44] NOTICE: exiting, bye-bye!
```

**Comment by ebrearley** [comment] 2024-07-09 05:47
This just happened to me... twice. Once yesterday and again today while i was rebuilding the crashed Coolify setup. Both times have completely crippled Coolify and all applications running on the host. The Coolify container is absent after rebooting the host.

The first time it happened, it seemed out of the blue.

The second time it happened as soon as I tried to map `/data` from the host to into a container running [OpenVSCode](https://docs.linuxserver.io/images/docker-openvscode-server). Purpose for doing this was to add some yaml config files to the proxy in order to set up a Traefik forwardAuth middleware. Which I did with my previous coolify setup, seemingly without issue - until I crashed the lot.

The host is a Ubuntu Server 24.04, fresh installed approximately an hour before the issue occurring.

<img width="690" alt="image" src="https://github.com/coollabsio/coolify/assets/10335665/479b354c-2cd9-4a8c-a0ad-b31d190ffedb">

Version: [v4.0.0-beta.306](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.306)

**Comment by ebrearley** [comment] 2024-07-16 12:11
I think I know what happened. I deleted a directory mount, and it deleted all the contents in the host path. Since I was mounting /data, removing this directory mount deleted the /data directory on the host, which is obviously catastrophic.

Perhaps deleting mounts should either not remove the data on the host, or, give the user a choice on whether to clear the data on the host.

**Comment by Telokis** [comment] 2024-07-23 17:31
Just happened to me as well in `v4.0.0-beta.317` (https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.317) when I tried to add a resource `Glance` to test the tool. (I have no other resource yet, it was the first attempt).

In my case it is a self-hosted version of Coolify on a server which already has a lot of containers running (and a Traefik already setup). Not sure if that is relevant or not. I am not sure whether the pass it specifies is supposed to be within the Coolify container or on my host server. (I'm only using a `localhost` server for now)

```
Error: Unable to create a directory at /var/www/html/storage/app/ssh/keys. (View: /var/www/html/resources/views/livewire/project/service/configuration.blade.php)
```

![image](https://github.com/user-attachments/assets/5a443600-9a44-4597-be70-95f660d47c80)

**Comment by dickeyy** [comment] 2024-07-28 10:27
`v4.0.0-beta.319`

The same issue just happened to me. All my services are (so far) still accessible but I can't use the coolify dashboard. It's very frustrating not to see any dev response here on how this can be fixed. 

Has anyone figured out how to resolve this issue? I have several large-scale mission-critical databases running and I'd like not to have to uninstall Coolify and re-set it up.

```
Error: Unable to create a directory at /var/www/html/storage/app/ssh/keys. (View: /var/www/html/resources/views/livewire/server/proxy/status.blade.php) (View: /var/www/html/resources/views/livewire/server/proxy/status.blade.php) (View: /var/www/html/resources/views/livewire/server/proxy/status.blade.php)
```

cc @andrasbacsai

**Comment by dickeyy** [comment] 2024-07-28 10:36
update:

I restarted the coolify docker container, it crashes with these as the last log lines

```
In UnableToCreateDirectory.php line 18:

  Unable to create a directory at /var/www/html/storage/app/ssh/keys.


s6-rc: warning: unable to start service init-script: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
[28-Jul-2024 10:32:25] NOTICE: Terminating ...
[28-Jul-2024 10:32:25] NOTICE: exiting, bye-bye!
```

**Comment by dickeyy** [comment] 2024-07-28 10:49
Fixed:

I followed the uninstall instructions in the [docs](https://coolify.io/docs/uninstall) but only steps 1 and 5, therefore not removing any of the data just the images. I then reinstalled following the same instructions in the docs. This seems to have worked. 

Still frustrating that this happened and the only viable fix was to uninstall and reinstall

**Comment by peaklabs-dev** [comment] 2024-10-24 17:45
I am not sure how we should reproduce this, so I am closing this issue. I added an [improvement request](https://github.com/coollabsio/coolify/discussions/4010)to prevent deletion of important directories like `/data` so this issue should be prevented. If this problem is still present or recurs, feel free to reopen this issue or start a new one with more detailed reproduction steps.

**Closed by peaklabs-dev** 2024-10-24 17:45 UTC
Labels: 🐛 Bug
