### ISSUE TITLE
[Bug]: Terminal session is not stopped when container stop

### ISSUE THREAD

**Issue by Vahor** [coollabsio/coolify#3519] opened 2024-09-20 14:17 UTC
### Error Message and Logs

Container terminal session is not stopped when container stop. Resulting in server access.

### Steps to Reproduce

1. Create an app using coolify like `nginx:latest`
2. Start the app
3. Connect to the terminal using the `Terminal` tab of the app
4. Check `hostname`, we are inside the container 
![image](https://github.com/user-attachments/assets/a17e3743-6383-4357-895d-8a5346a2e987)
5. Stop the app (using the stop button, and stay on the terminal page)
![image](https://github.com/user-attachments/assets/86dd6f42-e387-4cc4-a87a-d4292cd60eb1)
we have a ssh terminal outside of the container

### Coolify Version

v4.0.0-beta.341

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.1 LTS

### Additional Information

Not that huge of an issue as currently there's no permission to restrict access on the terminal. But in the future this could become a problem.

**Comment by andrasbacsai** [comment] 2024-09-25 08:28
This will be fixed in the upcoming version.

**Comment by LEstradioto** [comment] 2024-09-25 23:21
Actally, this is a complex topic. Some info here:

- Terminal is a nested ssh, first connect to main coolify container (PARENT PROCESS), then inside this process we run another ssh aiming to the selected container/server (CHILD PROCESS)
- when any process is killed or crash unexpectedly (SIGKILL), as in OP case, PARENT cant listen to this signal, so, its normal to terminal turns back to PARENT, but here we have an added complexity, because, cant catch any signals, because it is nested processes
- we are solving this listening on frontend if user types exit or CTRL+D, then we kill PARENT

---

- I think Andras will fix with a remotely reload the page if child container changes its status, is that right? I tried branch `next` and I couldnt reproduce this unfortunately
- alternatively we could add a hearbeat between child and parent (more complex though)
- or, we could use an Enable/disable checkbox to user choose if he wants to kill parent when typing exit or ctrl+D, maybe this would be more user-friendly

For anyone interested, here terminal flow:

![image](https://github.com/user-attachments/assets/874a214e-1de7-435c-a053-9d29afb1aa06)

**Closed** 2024-10-01 10:04 UTC
