### ISSUE TITLE
[Bug]: Container is not in same network as caddy

### ISSUE THREAD

**Issue by w3cj** [coollabsio/coolify#2066] opened 2024-04-25 05:45 UTC
### Description

Within a git based repo, if you choose an existing docker-compose file, there is no option to "connect to predefined network" like there is for service stacks.

I tried to add a custom domain to one of the services and the caddy proxy logs say: `Container is not in same network as caddy`

How can we use the caddy proxy / container labels for git based deployments with a pre-defined docker-compose.yml file in the repo?

### Minimal Reproduction (if possible, example repository)

1. Create a git based deployment.
2. Choose "Docker Compose" as the build pack
3. Choose your docker-compose file
4. Add a domain for one of the services in the docker-compose file

### Version

v4.0.0-beta.266

**Comment by andrasbacsai** [comment] 2024-04-25 08:35
I will add that option to apps as well, but it was caused by a different bug.

It will be fixed in the next version.

**Comment by andrasbacsai** [comment] 2024-04-25 09:43
Both. Caddy & and will add the option for apps. :)

**Closed** 2024-04-26 08:37 UTC
