### ISSUE TITLE
[Bug]: Cloudflare tunnels not working for SSH connections to servers

### ISSUE THREAD

**Issue by fabieu** [coollabsio/coolify#3314] opened 2024-09-04 22:14 UTC
### Description

I am trying to add a new server to my Coolify instance (tested with both self-hosted and cloud), while using Cloudflare Tunnels for the SSH connection. The server in question is a Raspberry Pi on my local network.

For configuration i followed the official documentation: https://coolify.io/docs/knowledge-base/cloudflare/tunnels

I have a healthy tunnel in Cloudflare Zero Trust with the following configuration:
![image](https://github.com/user-attachments/assets/8583884e-e940-42eb-89eb-5afb4c5da878)
![Screenshot_1](https://github.com/user-attachments/assets/5a9f8526-0efa-489b-be37-11e0ade11827)

The cloudflared agent is installed and running on my Raspberry Pi. I verified that the Cloudflare Tunnel is working as expected, by SSHing into to my Raspberry Pi via the cloudflared agent installed on my self-hosted instance (Ubuntu 24.04).

I also noticed, that for some reason the settings sometimes do not persist across page reloads when a configuration for Cloudflare Ttunnels has been set prior. I dont know, if this might be the cause of the problem.
![image](https://github.com/user-attachments/assets/e007b5f1-bb5b-45a1-9531-ec912f8d5bd0)
In this example the `Disk cleanup threshold (%)` and `Cloudflare Tunnels` configuration is empty, despite being present before.

Using Cloudflare Tunnels for HTTP/HTTPS bindings is working as expected, only the SSH connection to a server seems faulty.

### Minimal Reproduction (if possible, example repository)

**Reference**: https://coolify.io/docs/knowledge-base/cloudflare/tunnels

### Exception or Error

> [!NOTE]
> Actual domain changed to `ssh.example.com` for privacy
```text
Server is not reachable. Please validate your configuration and connection.
Check this [documentation](https://coolify.io/docs/knowledge-base/server/openssh) for further help.

Error: ssh: connect to host ssh.example.com port 22: Network is unreachable
```

### Version

v4.0.0-beta.325 and v4.0.0-beta.323

### Cloud?

- [X] Yes
- [X] No

**Comment by theraays** [comment] 2024-09-05 12:29
I had the same issue as yourself. My fix was to delete the ssh domain in cloudflare and not use the cloudflare settings in coolify. Now everything works as expected. Took me hours to fix this.

For the IP Address/Domain part, I put in the direct IP address and this allowed the server to connect without issues.

**Comment by djsisson** [comment] 2024-09-05 14:50
@fabisu, was the relevant CNAME entry also added to the cloudflare dns settings i.e sshxxx.tunnelid.cfargo.com

**Comment by djsisson** [comment] 2024-09-05 14:58
@fabieu i think if validation fails it drops back to that state .

just jsut to confirm, you never get a validated 2nd server?

**Comment by fabieu** [comment] 2024-09-05 17:06
> @fabieu i think if validation fails it drops back to that state .
> 
> just to confirm, you never get a validated 2nd server?

Correct, I can add other servers without the cloudflare tunnel configuration. Unfortunatly I did not get the Cloudflare Tunnel configuration to work inside Coolify. 

I want to clarify, that the Cloudflare Tunnel is working as expected, since I can connect with my cloudflared agent outside Coolify from the same instance (VM) that Coolify is running on. (see [Cloudflare Docs - Connect as a user](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/use-cases/ssh/#2-connect-as-a-user))

**Comment by Paarth-K** [comment] 2024-09-06 08:31
I'm having the same issues, services don't deploy and I get 
Error: ssh: connect to host ssh.example.com port 22: Network is unreachable.

**Comment by Paarth-K** [comment] 2024-09-06 08:40
Ok, reverting to 4.0.0-beta.325 (before the scp of compose files) fixes things.

**Comment by fabieu** [comment] 2024-09-06 08:46
> Ok, reverting to 4.0.0-beta.325 (before the scp of compose files) fixes things. 

The version you are mentioned cant be the right one. I tested 4.0.0-beta.323 and 4.0.0-beta.325.

**Comment by Paarth-K** [comment] 2024-09-06 09:57
I think then we have different bugs, but the same error. My bug occurs when I try and deploy a resource on a server using cloudflare tunnels (which could be caused by the new SCP transfer of compose files).

**Comment by mrcleanandfresh** [comment] 2024-09-07 22:25
> Ok, reverting to 4.0.0-beta.325 (before the scp of compose files) fixes things.

This fixed my issue. I upgraded to the latest Beta (331, I think?) and couldn't save settings for my services. I'd click save, and it'd hang and hang, then a toast would pop up saying, "error: ssh: connect to host ssh-test.xxxx port 22: network is unreachable lost connection" I checked cloudflare tunnels and everything was healthy. I re-installed the same version of coolify via ssh, that didn't help. So I restarted my server, that didn't help either. When I would skip saving settings and just click "Deploy" it would hang and hang on the drawer that slides out to show logs.

Finally downgraded per this suggestion, and it fixed all these issues.

**Comment by fabieu** [comment] 2024-09-10 16:06
### Update: I got the Cloudflare Tunnels to work. But I think due to the server validation mentioned by @djsisson , it requires a carefully executed set of actions:

**- Add a new server:**
![image](https://github.com/user-attachments/assets/ef870c44-238d-48b2-8e7c-877ea0a77091)

Make sure to not press validate yet!

**- Configure Server Timezone and Cloudflare Tunnels**
![image](https://github.com/user-attachments/assets/5f4c6949-f289-4f5c-8956-b337607040a1)

**- Press "Save"**
![image](https://github.com/user-attachments/assets/ca607dd0-cfd7-4f37-9722-30df10babcbc)

Do not open the configuration for Cloudflare Tunnel again at this point!

**Now press Validate Server & Install Docker Engine**

Any page refresh or different interaction then described above might result in a failure of the Cloudflare Tunnel Configuration.

Can this be prevented?

**Comment by andrasbacsai** [comment] 2024-09-12 10:39
This will be fixed in the upcoming version.

**Closed** 2024-09-12 10:43 UTC
Labels: 🐞 Bug
