### ISSUE TITLE
[Enhancement]: Confirmation Settings background stays black for Light Mode

### ISSUE THREAD

**Issue by majnioui** [coollabsio/coolify#4235] opened 2024-11-10 21:47 UTC
### Request Type

Improvement

### Description

Hi;

This is a small adjustment, the **Confirmation Settings** background stays black when switching the color setting to Light mode which prevents it from being seen correctly  as you can see in the screenshot below

![Image](https://github.com/user-attachments/assets/24b32293-a755-4936-b25f-a5d909265b20)

**Comment by peaklabs-dev** [comment] 2024-11-10 21:58
Duplicate of #4216

**Closed by peaklabs-dev** 2024-11-10 21:58 UTC
Labels: 🔍 Triage, ✨ Enhancement
