### ISSUE TITLE
[Bug]: Error when saving env file in developer view

### ISSUE THREAD

**Issue by luuductue** [coollabsio/coolify#1391] opened 2023-11-06 03:47 UTC
### Description

![image](https://github.com/coollabsio/coolify/assets/144940355/e9b2e5d9-f0b3-4a10-8acc-2045a85a9025)

i got this error same with other people when trying to save env in developer view 

### Minimal Reproduction (if possible, example repository)

save env in developer view

### Version

v4.0.0-beta.108

**Comment by andrasbacsai** [comment] 2023-11-06 07:57
Duplicate of #1378 (will be fixed in the upcoming version)

**Closed by andrasbacsai** 2023-11-06 07:57 UTC
