### ISSUE TITLE
The environment variables are not binding, I read the document but not work.

### ISSUE THREAD

**Issue by BirajMainali** [coollabsio/coolify#2739] opened 2024-07-03 03:21 UTC
### Description

**Shared environment variable inside production**  
![image](https://github.com/coollabsio/coolify/assets/71131016/4a8956c4-6c24-4b47-9898-da03b1501e7b)
**Environment variable config used in application**
![image](https://github.com/coollabsio/coolify/assets/71131016/2d84be44-3ea5-4daf-83e4-bb909b7e18e6)
**And the environment variable looks like**

### Minimal Reproduction (if possible, example repository)

server={{ production.SQL_HOST }},{{ production.SQL_PORT }};database=xyz;User ID={{ production.SQL_USER }}; Password={{ production.SQL_PASSWORD }}

### Version

current beta

**Comment by knurzl** [comment] 2024-07-03 16:59
dont write current beta... what is current beta..? could be something else in some time.

**Comment by knurzl** [comment] 2024-07-03 17:00
but same issue over here at least for preview deployments.

**Comment by wallaceosmar** [comment] 2024-07-04 18:10
The problem is using production like {{ production.SQL_HOST }}
```
server={{ environment.SQL_HOST }},{{ environment.SQL_PORT }};database=xyz;User ID={{ environment.SQL_USER }}; Password={{ environment.SQL_PASSWORD }}
```

**Comment by birajmainaliquickfox** [comment] 2024-07-05 04:24
> The problem is using production like {{ production.SQL_HOST }}
> 
> ```
> server={{ environment.SQL_HOST }},{{ environment.SQL_PORT }};database=xyz;User ID={{ environment.SQL_USER }}; Password={{ environment.SQL_PASSWORD }}
> ```

I have tried all the possible ways, but not works

**Comment by BirajMainali** [comment] 2024-07-05 13:59
> The problem is using production like {{ production.SQL_HOST }}
> 
> ```
> server={{ environment.SQL_HOST }},{{ environment.SQL_PORT }};database=xyz;User ID={{ environment.SQL_USER }}; Password={{ environment.SQL_PASSWORD }}
> ```

I have tried every single possible way, but first thing the doc is not , I think Coolify will resolve this issue very soon Because I have installed Coolify on my server where I have 100+ client are live,

**Comment by developomp** [comment] 2024-09-09 11:31
Possible duplicate of #2169

**Comment by peaklabs-dev** [comment] 2024-10-28 16:56
You need to use `environment.VARIABLE` not your actual environment name. Also if you want to use it with compose files use it as I described in the following comment https://github.com/coollabsio/coolify/issues/2169#issuecomment-2442123874.

**Closed by peaklabs-dev** 2024-10-28 16:56 UTC
