### ISSUE TITLE
[Bug]: Duplicate Table Error During Migration in Coolify Deployment | latest working Version 4.0.0-beta.323

### ISSUE THREAD

**Issue by Procuria** [coollabsio/coolify#3618] opened 2024-09-28 15:52 UTC
### Error Message and Logs

I encountered an issue while deploying Coolify, where the process fails due to a duplicate table error during the migration step. Below are the details and error logs:

#### Docker Logs coolify container:  
````sql
SSL_MODE has been DISABLED, setting the web server to work in HTTP only...
ERROR The [public/storage] link already exists.
INFO Running migrations.
...
SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "telescope_entries" already exists 
(Connection: pgsql, SQL: create table "telescope_entries" ("sequence" bigserial not null primary key, "uuid" uuid not null, 
"batch_id" uuid not null, "family_hash" varchar(255) null, "should_display_on_index" boolean not null default '1', 
"type" varchar(20) not null, "content" text not null, "created_at" timestamp(0) without time zone null))

In Connection.php line 825:
SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "telescope_entries" already exists
```` 
#### Docker Logs postgres container:
  ````vbnet
2024-09-28 15:39:08.587 UTC [197] ERROR: current transaction is aborted, commands ignored until end of transaction block
2024-09-28 15:39:15.657 UTC [205] ERROR: relation "telescope_entries" already exists
````

### Steps to Reproduce

1. Deploy Coolify using the current configuration.
2. Observe the migration process failing with the above errors.
3.
4.

### Coolify Version

v4.0.0-beta.323 

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04.4 

### Additional Information

Expected Behavior: The migration process should handle existing tables gracefully and complete without errors.

Actual Behavior: The deployment fails due to a duplicate table error, specifically related to the "telescope_entries" table already existing.

Possible Cause: It seems like the migration script attempts to create a table that already exists in the database, causing the deployment to fail.  

If there are any configurations or steps I can adjust to mitigate this issue, please let me know.

**Comment by andrasbacsai** [comment] 2024-09-28 17:04
Did you ever installed a non-released version (`next`)? Because it looks like you did.

There is only one migration available that looks good and I cannot reproduce this issue.

**Comment by Procuria** [comment] 2024-09-28 17:11
@andrasbacsai Thank you very much for the fast reply! 
I think I once installed a next version — but I thought that should not be an issue, as I'm using a DB backup from before. 
But I'm not completely certain about that. 
Would you be so kind to elaborate on what gave you that clue regarding the  _non-released_ version? 
What do you mean by “There is only one migration available that looks good”?
What would you suggest doing, in order having an upgradable instance again?

**Comment by Procuria** [comment] 2024-10-10 08:06
Unfortunately I still need support regarding this issue. 
Should I convert this issue to a discussion topic?

**Comment by peaklabs-dev** [comment] 2024-10-10 21:00
I think as you have kind of broken your database, I would suggest just doing a fresh install. You could ask for more help on discord, but I doubt anyone will be able to help you there (link them to this issue please). As this is not a problem/bug in Coolify I will close this.

**Closed by peaklabs-dev** 2024-10-10 21:00 UTC

**Comment by Procuria** [comment] 2024-10-11 10:22
Thank you for taking the time, and thank you for this awesome project. 

If someone has the same problem, here is how I solved it:

0. __!!! Have database backup of your last working version !!!__
1. stop the Coolify Docker-Compose project and remove the _coolify-db_ docker volume 
2. use the `update.sh` to install Coolify - add the `4.0.0-beta.xxx` with the desired version at execution
````bash
./update.sh 4.0.0-beta.358
````
3. stop the _coolify_ container
4. copy your dump into the _coolify-db_ container 
````
docker cp /path/to/dump.dmp coolify-db:/opt/dump.dmp
````
5. head inside your _coolify-db_ container
````
docker exec -it coolify-db /bin/bash
````
6. restore your dump
````
pg_restore --verbose --clean -h localhost -U coolify -d coolify /opt/dump.dmp
```` 
7. head into the db with `psql -U coolify` and clean the db of _telescope\__ entries 
````sql
DO $$ 
DECLARE 
    r RECORD; 
BEGIN 
    FOR r IN (SELECT sequence_name FROM information_schema.sequences WHERE sequence_name LIKE 'telescope_%') 
    LOOP 
        EXECUTE 'DROP SEQUENCE IF EXISTS ' || quote_ident(r.sequence_name) || ' CASCADE'; 
    END LOOP; 
END $$;
````
8. check for "remnants" regarding tables, sequences and constraints - there should be 0 rows
````sql
SELECT tablename FROM pg_tables WHERE tablename LIKE 'telescope_%';
SELECT sequence_name FROM information_schema.sequences WHERE sequence_name LIKE 'telescope_%';
SELECT conname FROM pg_constraint WHERE conname LIKE 'telescope_%';
````
9. start the _coolify_ container again. 
10. Upgrade happy everly after 🤓

**Comment by Procuria** [comment] 2024-10-11 10:39
Of course. I'm happy if it helps.
And thank you again for being so approachable!
