### ISSUE TITLE
[Bug]: ssh: connect to host host.docker.internal port 22

### ISSUE THREAD

**Issue by daraeowl** [coollabsio/coolify#3267] opened 2024-08-30 20:58 UTC
### Description

Hello, I'm trying to solve this error on the Servers part of the web/ui
![image](https://github.com/user-attachments/assets/b854d585-96e1-4c7e-8a25-5605ab6cb217)

I keep getting this error
![image](https://github.com/user-attachments/assets/32e29145-8e6d-4142-843c-7e000b8274b0)

my ufw status shows port 22/tcp enabled with all of the requiered ports for coolify

### Minimal Reproduction (if possible, example repository)

curl -fsSL https://cdn.coollabs.io/coolify/install.sh | sudo bash 

### Exception or Error

Server is not reachable.

Please validate your configuration and connection.

Check this [documentation](https://coolify.io/docs/knowledge-base/server/openssh) for further help. 

Error: ssh: connect to host host.docker.internal port 22: Connection refused

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by fanpero87** [comment] 2024-09-03 19:10
I had the same problem. Used UFW to allow SSH over my VPN IP. I fix it like this:
- Added a second rule to allow the server IP to port 22
- Restart the coolify docker image

After that, I was able to connect to the GUI and it connected to Localhost.

**Comment by peaklabs-dev** [comment] 2024-11-20 22:08
Since we have made a lot of changes to SSH and the validation process, I will close this issue. If this issue comes up again, feel free to reopen or create a new issue.

**Closed by peaklabs-dev** 2024-11-20 22:08 UTC

**Comment by rulrok** [comment] 2024-12-19 22:12
I am trying this out and just stumbled upon the same problem.
Changing the rules with UFW worked.

I'm using version `beta.379`

**Comment by stag-enterprises** [comment] 2025-01-13 02:37
I also have this issue

**Comment by anbarasanv** [comment] 2025-02-09 06:34
I'm having the same issue:

Please validate your configuration and connection.

Check this [documentation](https://coolify.io/docs/knowledge-base/server/openssh) for further help. 

Error: ssh: connect to host host.docker.internal port 22: Connection refused

**Version**
v4.0.0-beta.390

**Comment by flawnn** [comment] 2025-02-18 21:39
Why can't we change the SSH Port that is being used? There is a reason I have the SSH Port on 22 closed O.o

**Comment by Yossri21** [comment] 2025-02-23 01:16
I am facing the same issue

**Comment by stag-enterprises** [comment] 2025-02-28 14:03
@rulrok Could you share how you fixed the issue with UFW? Thanks!

**Comment by yacc** [comment] 2025-03-25 19:04
Also, check your sshd settings, if you have hardened your server, that might be interfering.
For example I had these rules:
```sh
root@coolify-server:/data/coolify/source# cat /etc/ssh/sshd_config.d/custom.conf
Port 22
PermitRootLogin no
PasswordAuthentication no
X11Forwarding no
MaxAuthTries 3
AllowUsers johndoe
```
and both `PermitRootLogin no` and `AllowUsers johndoe` were interfering.
It worked after changing to:
```sh
root@coolify-server:/data/coolify/source# cat /etc/ssh/sshd_config.d/custom.conf
Port 22
PermitRootLogin yes
PasswordAuthentication no
X11Forwarding no
MaxAuthTries 3
AllowUsers johndoe root
```

**Comment by stag-enterprises** [comment] 2025-03-25 19:12
I've checked my sshd settings, and I don't believe I have anything that would cause issues. This is mine for reference
```
Include /etc/ssh/sshd_config.d/*.conf
Port 22
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
LogLevel VERBOSE
Subsystem sftp  internal-sftp -f AUTHPRIV -l INFO
Protocol 2
X11Forwarding no
PermitEmptyPasswords no
IgnoreRhosts yes
HostbasedAuthentication no
UseDNS yes
ClientAliveCountMax 20
ClientAliveInterval 2000
LoginGraceTime 5
MaxAuthTries 2
MaxSessions 20
MaxStartups 10:30:50
PermitRootLogin yes
MaxAuthTries 4
PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
UsePAM yes
PrintMotd no
ClientAliveInterval 30
ClientAliveCountMax 50
AcceptEnv LANG LC_*
```

**Comment by drjimmy1990** [comment] 2025-05-25 03:39
anyone could fix that please ?

**Comment by ouariachi** [comment] 2025-06-13 08:22
I have fixed it this way:

1. Found the Coolify container IP:
```bash
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' coolify
````

2. Allowed SSH from that IP in UFW:

```bash
sudo ufw allow from <container_ip> to any port 22 proto tcp
```
3. Verified UFW status.

4. Confirmed Coolify’s SSH public key was in the host user’s `authorized_keys`.

5. Configured Coolify to use the correct SSH user and private key.

Now Coolify connects properly to the host via SSH inside Docker.

**Comment by nivla360** [comment] 2025-07-10 11:53
> I have fixed it this way:
> 
> 1. Found the Coolify container IP:
> 
> docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' coolify
> 2. Allowed SSH from that IP in UFW:
> 
> sudo ufw allow from <container_ip> to any port 22 proto tcp
> 3. Verified UFW status.
> 4. Confirmed Coolify’s SSH public key was in the host user’s `authorized_keys`.
> 5. Configured Coolify to use the correct SSH user and private key.
> 
> Now Coolify connects properly to the host via SSH inside Docker.

Thanks a lot bro, this works

**Comment by komali2** [comment] 2025-07-23 08:04
I'm having this issue on a fresh ubuntu 22.04 install. 

My port is slightly different, 3777, just to prevent random bots (it's not actually that btw). 

However, I've updated ufw to account for this, and try changing the port in the onboarding to account for this as well. 

```
ssh: connect to host host.docker.internal port 3777: Connection refused
```

(Same for 22, for what it's worth)

My sshd config: 

```

Include /etc/ssh/sshd_config.d/*.conf

Port 3777
PermitRootLogin prohibit-password
PubkeyAuthentication yes

PasswordAuthentication no
ChallengeResponseAuthentication no
UsePAM yes
X11Forwarding yes
PrintMotd no
AcceptEnv LANG LC_*
Subsystem sftp  /usr/lib/openssh/sftp-server
PasswordAuthentication no
```

I have the pubkey in `/root/.ssh/authorized_keys`

I have reset sshd after applying changes. 

I have run `sudo ufw allow from {docker ip} to any port 3777 proto tcp` (and 22 fwiw)

Not sure what to try next. I can ssh in as root, as well as 2 other users I tested creating, from a terminal.

**Comment by plowsof** [comment] 2025-11-17 15:45
thanks all for feedback here - had the same issue, but it was intermittent - sometimes it was able to access the server via ssh and deploy things but then other times not. After switching from the default port (22) to another - the problem has gone (internet background noise interfering? im not sure)

**Comment by oestrada1001** [comment] 2025-11-23 08:20
I had a similar issue but I was deploying private repository with github app on a docker-compose.yml.

I'm using one server to deploy multiple applications. 

I had to grant my internal docker container IP access to the port 22.

These are the commands I ran:
1. `ufw status` - This allowed me to verify that port 22 wasn't open to the whole world. My status for port 22 was LIMIT
2. Then I ran `ufw status verbose` - I was able to verify that I had logging on.
3. Then I ran `tail -f /var/log/ufw.log` and was able to find the internal IP that was attempting to access port 22 but was being blocked. Example: (10.0.0.4)
4. Lastly, I ran `sudo ufw allow proto tcp from 10.0.0.4 to any port 22`

**Comment by dextr27125** [comment] 2025-12-04 13:02
This commands helped me:

**3. Firewall (UFW) Blocking Docker**
Coolify makes heavy use of SSH connections, and UFW rate limiting can block them.  If you're using UFW:
bash# Check status
sudo ufw status

# Allow SSH from Docker network
sudo ufw allow from 172.16.0.0/12 to any port 22
sudo ufw allow from 192.168.0.0/16 to any port 22

**Comment by GuillermoDLCO** [comment] 2026-02-01 16:10
> I have fixed it this way:
> 
> 1. Found the Coolify container IP:
> 
> docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' coolify
> 2. Allowed SSH from that IP in UFW:
> 
> sudo ufw allow from <container_ip> to any port 22 proto tcp
> 3. Verified UFW status.
> 4. Confirmed Coolify’s SSH public key was in the host user’s `authorized_keys`.
> 5. Configured Coolify to use the correct SSH user and private key.
> 
> Now Coolify connects properly to the host via SSH inside Docker.

Thank you, it worked. I have several servers but only in one I got this issue. Additionally I also needed to set env variable `NIXPACKS_NODE_VERSION=22` to fix nix build.
