### ISSUE TITLE
[Bug]: Secrets with spaces do not work

### ISSUE THREAD

**Issue by chikof** [coollabsio/coolify#922] opened 2023-02-14 00:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When I create a secret with a value containing spaces, the secret is not registered.

### Steps To Reproduce

1. Create a secret, the name doesn't matter
2. Put a value with spaces, in my case "462780441594822687 893135042111479808"
3. Deploy the application
4. Try to get the Secret

### Version

3.12.17

**Comment by ChikoShidori** [comment] 2023-02-18 15:14
Nvm

**Comment by ChikoShidori** [comment] 2023-02-18 15:18
xD, I though it was something else, but yea, it's a bug

**Comment by MartinKavik** [comment] 2023-02-20 16:05
The same problem with newlines - e.g. a public key like the one below is not usable in Coolify:
```
-----BEGIN PUBLIC KEY-----
abcd
efgh
-----END PUBLIC KEY-----
```

**Comment by davidwinter** [comment] 2023-08-16 18:31
I can confirm I'm experiencing the same issue, and currently my workaround is to base64 encode the value and decode it within the app. Though that isn't always possible with 3rd party docker images/apps.

**Comment by davidwinter** [comment] 2023-08-16 18:32
@andrasbacsai was this resolved elsewhere? I see the issue was unassigned so I'm just curious. Thanks.

**Comment by andrasbacsai** [comment] 2023-09-08 09:14
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.

**Closed** 2023-09-08 09:14 UTC
