### ISSUE TITLE
[Feature Request] Gitea as Git source

### ISSUE THREAD

**Issue by tacohitbox** [coollabsio/coolify#162] opened 2022-02-21 07:28 UTC
Self explanatory. Not a must-have immediately but would be cool to have :)

**Comment by andrasbacsai** [comment] 2022-02-21 07:45
Thanks for the PR, I will add support for Gitea for sure! 

I'm closing this as it's a duplicate of #130 . :)

**Closed by andrasbacsai** 2022-02-21 07:45 UTC

**Comment by mmm8955405** [comment] 2023-02-23 03:37
> Thanks for the PR, I will add support for Gitea for sure!
> 
> I'm closing this as it's a duplicate of #130 . :)
This is not a copy at all
