### ISSUE TITLE
[Bug]: Execute command endpoint commented out

### ISSUE THREAD

**Issue by AroPix** [coollabsio/coolify#4544] opened 2024-12-11 16:11 UTC
### Error Message and Logs

Response of 404 from the endpoint.

### Steps to Reproduce

1.Try to execute command using /execute endpoint
2.Response is 404

### Coolify Version

v4.0.0-beta.376

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Almalinux 9.5

### Additional Information

The execute command endpoint doesn't work as it is commented out in the code:
https://github.com/coollabsio/coolify/blob/8d779c88ff4f4709ac0353713533a65fe7d0b86c/routes/api.php#L91

**Comment by peaklabs-dev** [comment] 2024-12-11 16:28
Duplicate of #4312

**Closed by peaklabs-dev** 2024-12-11 16:28 UTC
