### ISSUE TITLE
[Bug]: 500 Error Occurred After Adding Scheduled Task to the Project

### ISSUE THREAD

**Issue by harryxu** [coollabsio/coolify#2956] opened 2024-07-26 13:40 UTC
### Description

500 Error occurred after adding scheduled task to a project's resource

### Minimal Reproduction (if possible, example repository)

On `Projects` - `production` - `Resource name`, then click `Scheduled Tasks`.  
After adding a task, this error page appears.

And every time I enter the `Scheduled Tasks` page afterward, I see an error and cannot use the features normally.

### Exception or Error

```
500

Something is not okay, are you okay?
There has been an error, we are working on it.

Error: Missing required parameters for [Route: project.service.scheduled-tasks] [URI: project/{project_uuid}/{environment_name}/service/{service_uuid}/tasks/{task_uuid}] [Missing parameters: project_uuid, environment_name, service_uuid]. (View: /var/www/html/resources/views/livewire/project/shared/scheduled-task/all.blade.php)
```

### Version

v4.0.0-beta.318

### Cloud?

- [ ] Yes
- [X] No

**Comment by peaklabs-dev** [comment] 2024-08-20 14:38
@harryxu Can you please update to the latest version and recheck and if possible provide more detailed reproduction steps? Thank you.

**Comment by harryxu** [comment] 2024-08-23 08:55
I upgrade to version v4.0.0-beta.323, now the Scheduled Task page is working, no error anymore.

But the Recent executions text color is difficult to see in light mode.

Light Mode:
<img width="877" alt="image" src="https://github.com/user-attachments/assets/f9887636-02a3-4032-b9e3-9b71db85f288">

Dark Mode:
<img width="802" alt="image" src="https://github.com/user-attachments/assets/652a4b74-a6d5-4b13-a844-7cbd83637162">

**Comment by peaklabs-dev** [comment] 2024-08-23 10:04
@harryxu Amazing. I already fix the color issue in this PR:  https://github.com/coollabsio/coolify/pull/3063
Preview:
![image](https://github.com/user-attachments/assets/aa482745-5d58-47bc-b186-7255d6b83e21)

Since this is fixed, I will close this issue (and the color issue has a separate bug report anyway).

**Closed by peaklabs-dev** 2024-08-23 10:04 UTC
Labels: 💤 Waiting for feedback
