### ISSUE TITLE
[Bug]: Minio template error "The string `:9001` is no a valid url."

### ISSUE THREAD

**Issue by che0one** [coollabsio/coolify#4229] opened 2024-11-10 07:06 UTC
### Error Message and Logs

It seems impossible to add or save the actual MinIO template or integrate it over "New Resource -> Docker Compose Empty" with or without other containers due to an issue related to ":9001" part. The error message, "The string :9001 is not a valid URL," doesn't prevent saving the Compose configuration to Coolify Projects, but makes it impossible to save the MINIO_SERVER_URL and $MINIO_BROWSER_REDIRECT_URL variables or change other things...

Default minio template from Services list
```
services:
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_SERVER_URL=$MINIO_SERVER_URL
      - MINIO_BROWSER_REDIRECT_URL=$MINIO_BROWSER_REDIRECT_URL
      - MINIO_ROOT_USER=$SERVICE_USER_MINIO
      - MINIO_ROOT_PASSWORD=$SERVICE_PASSWORD_MINIO
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 20s
      retries: 10
```
![Image](https://github.com/user-attachments/assets/9b7ec593-b761-48a3-bcbb-eaa9349c14c8)

### Steps to Reproduce

1. Copy Minio Template from Services List
2. Try to make new resource using Docker Compose Empty

### Example Repository URL

https://github.com/coollabsio/coolify/blob/main/templates/compose/minio.yaml

### Coolify Version

v4.0.0-beta.364

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04 & Alpine-Linux:Latest & Ubuntu 24.04 ARM

**Comment by chmielulu** [comment] 2024-11-11 13:00
Changing the “:9001” part to, for example, “:8000” still gives the same error “The string :9001 is not a valid URL,” so it looks like the problem is not in the template itself. 

I tried specifying the port also using an environment variable, such as:
```yaml
services:
  minio:
    image: 'quay.io/minio/minio:latest'
    command: 'server /data --console-address ":${MINIO_CONSOLE_PORT}"'
    environment:
      - MINIO_SERVER_URL=$MINIO_SERVER_URL
      - MINIO_BROWSER_REDIRECT_URL=$MINIO_BROWSER_REDIRECT_URL
      - MINIO_ROOT_USER=$SERVICE_USER_MINIO
      - MINIO_ROOT_PASSWORD=$SERVICE_PASSWORD_MINIO
      - MINIO_CONSOLE_PORT=9001
    volumes:
      - 'minio-data:/data'
    healthcheck:
      test:
        - CMD
        - mc
        - ready
        - local
      interval: 5s
      timeout: 20s
      retries: 10
```
I then get the same error again and again, even after changing the port to a different one.

**Comment by chmielulu** [comment] 2024-11-11 13:35
I managed to set up Minio by following these steps:

1. Created a new Minio resource but encountered the following error:  
   **`The string :9001 is not a valid URL`**.
   
2. Edited the Docker Compose configuration for the resource and temporarily switched the image:  
   From: `'quay.io/minio/minio:latest'`  
   To: `'bitnami/minio:latest'`.

3. Triggered the deployment with the updated configuration.

4. Once the deployment completed, reverted the image back to:  
   `'quay.io/minio/minio:latest'`.

5. Deployed again. After this step, Minio started working as expected, even with the following command:  
   ```yaml
   command: 'server /data --console-address ":9001"'

**Comment by LaurenceJJones** [comment] 2024-11-11 14:59
So tracing back through the code it seems the error may stem from here:

https://github.com/coollabsio/coolify/blob/cb433dddc4cc78a5c03926541554069a57d5262c/bootstrap/helpers/docker.php#L241-L244

Since the variables will be blank upon a new deployment, coolify tries to validate the URL is in fact a URL but `:<port>` does not pass the validation check.

And using the same logic the issue will also effect the `logto` deployment also.

**Comment by andrasbacsai** [comment] 2024-11-12 11:59
This will be fixed in the next version.

**Closed** 2024-11-15 11:36 UTC
Labels: 🐛 Bug, 🔍 Triage
