### ISSUE TITLE
[Bug]: Mixed content when deployed behind LB

### ISSUE THREAD

**Issue by aimestereo** [coollabsio/coolify#2518] opened 2024-06-13 06:05 UTC
### Description

I have a problem with Coolify admin. It is deployed on AWS EC2 and SSL termination happens before traffic reaches instance.

In my setup Coolify thinks that it's served via `http` and hardcode `http` into generated pages.

How do I teach Coolify that it's behind https? what am I missing?

Notes:

* To do any configurations I access site via `http://` by direct link. via `https://my.domain` i can' use it, since UI is completely broken

after I've created this issue, I've found [dns configuration](https://coolify.io/docs/knowledge-base/dns-configuration), so I've set `Settings -> General -> Instance's Domain` to my `https://my.domain` that I use to access instance - nothing changed, except this:

```html
Validating DNS failed.
<br><br>
Make sure you have added the DNS records correctly.
<br><br>
https://coolify.truagents.dev->host.docker.internal
<br><br>
Check this <a target='_blank' class='underline dark:text-white' href='https://coolify.io/docs/knowledge-base/dns-configuration'>documentation</a> for further help.
```

I've also tried to disabled Domain validation - it let me save settings, but it didn't help with overall problem

### Minimal Reproduction (if possible, example repository)

I have such deployment  in AWS:
`- https ->` CloudFront (terminate ssl) `- http ->` LoadBalancer -> EC2 with Coolify

### Exception or Error

Example: part of Server page - see a lot of `http://`:

```html
<title>Coolify</title>
<link rel="icon" href="http://coolify.truagents.dev/coolify-transparent.png" type="image/x-icon" />
...
<link rel="preload" as="style" href="http://coolify.truagents.dev/build/assets/app-f77813ca.css" />
<link rel="modulepreload" href="http://coolify.truagents.dev/build/assets/app-4ed993c7.js" />
<link rel="stylesheet" href="http://coolify.truagents.dev/build/assets/app-f77813ca.css" data-navigate-track="reload" />
<script type="module" src="http://coolify.truagents.dev/build/assets/app-4ed993c7.js" data-navigate-track="reload"></script> 
```

<img width="1085" alt="image" src="https://github.com/coollabsio/coolify/assets/2869535/e35fa7f1-267f-4cfc-8a55-494a07b45b63">

<img width="1082" alt="Screenshot 2024-06-13 at 08 55 19" src="https://github.com/coollabsio/coolify/assets/2869535/e35eeb3e-96ac-45ae-90e7-10596b02efe6">

### Version

v4.0.0-beta.294

**Comment by stuart-haas** [comment] 2024-06-26 02:10
@aimestereo Have you considered using a network load balancer instead and terminating SSL on the server? This seems like a simple configuration issue between cloudfront and your ec2 instance. The server you are running should expose another port for 443 or 9443 and then you can forward that traffic to a network load balancer and/or use cloudfront in front of that to handle ssl traffic.

**Comment by aimestereo** [comment] 2024-06-28 10:00
@stuart-haas, thanks, I will try it out, originally I just thought that I misconfigured Coolify, but it seems, for https to work correctly I need to let Coolify to terminate SSL

**Comment by bh0mbalziyad** [comment] 2024-10-16 05:55
Can confirm that this is indeed solved by letting traefik terminate the SSL connection. I initially had Coolify deployed behind Nginx and wasn't using Traefik but that setup wasn't ideal as I was having to spend an unreasonable amount of time on rewriting my Nginx rules.

**Comment by aimestereo** [comment] 2024-10-24 11:00
@bh0mbalziyad if you don't mind, can you share your Traefik config? I don't see much difference in how I terminate SSL: on ALB, Nginx or Traefik.

**Comment by bh0mbalziyad** [comment] 2024-10-24 12:27
@aimestereo I'm using the default configuration which coolify autogenerates, the only change I've made was to add a dynamic configuration to include SSL certificates

```yaml
tls:
    certificates:
        - certFile: /traefik/certs/wildcard.cert
          keyFile: /traefik/certs/wildcard.key
```

**Comment by peaklabs-dev** [comment] 2024-10-28 13:16
I think this issue is resolved by looking at the comments/ not a bug of Coolify itself more of a configuration problem so I will close this issue.

**Closed by peaklabs-dev** 2024-10-28 13:16 UTC
