### ISSUE TITLE
Getting error while installing coolify

### ISSUE THREAD

**Issue by heyarviind** [coollabsio/coolify#27] opened 2021-04-10 05:02 UTC
I am getting an error after adding the domain name and email address. please check the screenshot below

![Screenshot 2021-04-10 at 10 30 07 AM](https://user-images.githubusercontent.com/21043614/114258953-fe6d4080-99e7-11eb-92bd-854a579c4c7a.png)

**Comment by andrasbacsai** [comment] 2021-04-10 09:42
Can you please re-run the script with the debug option (2)?

**Comment by heyarviind** [comment] 2021-04-10 09:51
Getting the same error with option 2
![Screenshot 2021-04-10 at 3 19 46 PM](https://user-images.githubusercontent.com/21043614/114265780-5b7cec80-9a10-11eb-97d5-5bc5ce7933f8.png)

**Comment by heyarviind** [comment] 2021-04-10 09:52
It's a fresh Digitalocean droplet with Ubuntu 20.04

**Comment by andrasbacsai** [comment] 2021-04-10 11:24
Thanks. I know what the problem is. I've updated the installer so that it will output the cause - hopefully.

It looks like your domain name cannot be checked against the DNS server.
If you run the following command: `dig @1.1.1.1 A <domain> +short` but replace <domain> with your actual domain, it should not get back anything (no output).

**Comment by heyarviind** [comment] 2021-04-10 18:02
umm okay, is it possible to use coolify without adding the domain? because my droplet IP is static and it won't change ever...

**Comment by andrasbacsai** [comment] 2021-04-12 09:32
Atm, it only works with a domain. I’ll check how it could work without it.

**Comment by icebob** [comment] 2021-04-14 13:39
You can use [nip.io](https://nip.io/) to make domain for IP addresses.

**Comment by andrasbacsai** [comment] 2021-04-20 18:59
Sorry, but there are too many things that need to be reviewed to use without HTTPS only through an IP address. 

Closing now, as the initial issue is solved.

**Closed by andrasbacsai** 2021-04-20 18:59 UTC
