### ISSUE TITLE
[Bug]: Nixpacks LICENSE collision between yarn and composer

### ISSUE THREAD

**Issue by Ashk2a** [coollabsio/coolify#4202] opened 2024-11-08 16:31 UTC
### Error Message and Logs

![Image](https://github.com/user-attachments/assets/66941ef6-8b79-4b59-b5e9-77efabd04527)

```
2024-Nov-08 16:15:00.909431
 > [ 4/13] RUN nix-env -if .nixpacks/nixpkgs-dbc4f15b899ac77a8d408d8e0f89fa9c0c5f2b78.nix && nix-collect-garbage -d:
2024-Nov-08 16:15:00.909431
31.94 building '/nix/store/jjnpvnpf29nm8mwvvzgihwgvgjncikf7-yarn.drv'...
2024-Nov-08 16:15:00.909431
32.00 Running phase: unpackPhase
2024-Nov-08 16:15:00.909431
32.00 unpacking source archive /nix/store/vlvg5xhhbjr9lpgqwz1a21pfaajz3xgx-yarn-1.22.22.tgz
2024-Nov-08 16:15:00.909431
32.03 source root is package
2024-Nov-08 16:15:00.909431
32.03 setting SOURCE_DATE_EPOCH to timestamp 499162500 of file package/preinstall.js
2024-Nov-08 16:15:00.909431
32.04 Running phase: installPhase
2024-Nov-08 16:15:00.909431
32.10 building '/nix/store/lkbk02hcrfnry61sa4l5hmkdpriq6hbz-php-with-extensions-8.3.10.drv'...
2024-Nov-08 16:15:00.909431
32.49 building '/nix/store/j6f9slv4j5lamszsjpyzj0bgg49lj5fw-dbc4f15b899ac77a8d408d8e0f89fa9c0c5f2b78-env.drv'...
2024-Nov-08 16:15:00.909431
32.57 error: collision between `/nix/store/diqxmvvwl3i7ps5gl55w3qvk9m1ny5ar-yarn/LICENSE' and `/nix/store/9l48l88x57rzxhkvv3y43wjky3wzbqh6-composer-2.7.7/LICENSE'
2024-Nov-08 16:15:00.909431
33.03 error: builder for '/nix/store/j6f9slv4j5lamszsjpyzj0bgg49lj5fw-dbc4f15b899ac77a8d408d8e0f89fa9c0c5f2b78-env.drv' failed with exit code 25
2024-Nov-08 16:15:00.909431
------
2024-Nov-08 16:15:00.909431
Dockerfile:8
2024-Nov-08 16:15:00.909431
--------------------
2024-Nov-08 16:15:00.909431
   6 |     
2024-Nov-08 16:15:00.909431
   7 |     COPY .nixpacks/nixpkgs-dbc4f15b899ac77a8d408d8e0f89fa9c0c5f2b78.nix .nixpacks/nixpkgs-dbc4f15b899ac77a8d408d8e0f89fa9c0c5f2b78.nix
2024-Nov-08 16:15:00.909431
   8 | >>> RUN nix-env -if .nixpacks/nixpkgs-dbc4f15b899ac77a8d408d8e0f89fa9c0c5f2b78.nix && nix-collect-garbage -d
2024-Nov-08 16:15:00.909431
   9 |     RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends curl wget
2024-Nov-08 16:15:00.909431
  10 |     COPY .nixpacks/assets /assets/
2024-Nov-08 16:15:00.909431
--------------------
2024-Nov-08 16:15:00.909431
ERROR: failed to solve: process "/bin/bash -ol pipefail -c nix-env -if .nixpacks/nixpkgs-dbc4f15b899ac77a8d408d8e0f89fa9c0c5f2b78.nix && nix-collect-garbage -d" did not complete successfully: exit code: 100
2024-Nov-08 16:15:00.914515
Deployment failed. Removing the new version of your application.
```

### Steps to Reproduce

1. Create a project with project repository
2. Use Nixpacks
3. Deploy

### Coolify Version

v4.0.0-beta.363

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04

### Additional Information

Following a deployment, I encountered this error. I rollback my branch to a working commit but the error persists now. I've tried to completely redo a new project, but the error persists.

**Comment by adrien-delhom** [comment] 2024-11-08 18:41
Temporary solution: I replaced yarn with npm and it works again.
The problem remains worrying, I'd like to have more info on what's going on :(

**Comment by Jeto143** [comment] 2024-11-08 18:56
Happens with pnpm as well:

> 2024-Nov-08 16:36:08.078509
66.30 Running phase: installPhase
2024-Nov-08 16:36:08.078509
67.84 building '/nix/store/chl7dvm3i2w6f7l6i3wn7shx5k3jcrir-dbc4f15b899ac77a8d408d8e0f89fa9c0c5f2b78-env.drv'...
2024-Nov-08 16:36:08.078509
68.00 error: collision between '/nix/store/yps0nmwa1mw15fdlqcfkm3mksq86nwpz-pnpm/LICENSE' and '/nix/store/19nk6m6mhw3171zc5s71xqd268mml88w-composer-2.7.7/LICENSE'
2024-Nov-08 16:36:08.078509
68.13 error: builder for '/nix/store/chl7dvm3i2w6f7l6i3wn7shx5k3jcrir-dbc4f15b899ac77a8d408d8e0f89fa9c0c5f2b78-env.drv' failed with exit code 25

**Comment by adrien-delhom** [comment] 2024-11-08 18:59
> Happens with pnpm as well:
> 
> > 2024-Nov-08 16:36:08.078509
> > 66.30 Running phase: installPhase
> > 2024-Nov-08 16:36:08.078509
> > 67.84 building '/nix/store/chl7dvm3i2w6f7l6i3wn7shx5k3jcrir-dbc4f15b899ac77a8d408d8e0f89fa9c0c5f2b78-env.drv'...
> > 2024-Nov-08 16:36:08.078509
> > 68.00 error: collision between '/nix/store/yps0nmwa1mw15fdlqcfkm3mksq86nwpz-pnpm/LICENSE' and '/nix/store/19nk6m6mhw3171zc5s71xqd268mml88w-composer-2.7.7/LICENSE'
> > 2024-Nov-08 16:36:08.078509
> > 68.13 error: builder for '/nix/store/chl7dvm3i2w6f7l6i3wn7shx5k3jcrir-dbc4f15b899ac77a8d408d8e0f89fa9c0c5f2b78-env.drv' failed with exit code 25

Ahaha I made the try 5mn ago, I confirm!

**Comment by JoaquinTrinanes** [comment] 2024-11-11 17:57
For anyone being unable to deploy, we managed to workaround the issue adding the following to the `nixpacks.toml` file:

```toml
[phases.setup]
nixPkgs = [
  "...",

  # https://nixos.org/manual/nixpkgs/stable/#var-meta-priority
  '(lib.recursiveUpdate php83Packages.composer { meta.priority = php83Packages.composer.meta.priority or 0 -1; })',
]
```

**Comment by peaklabs-dev** [comment] 2024-11-21 17:20
Can someone please provide me with a sample repository so I can analyze this. I think it is a configuration problem, but I would still like to investigate a bit more.

**Comment by JoaquinTrinanes** [comment] 2024-11-21 21:53
@peaklabs-dev I created a sample repo [over here](https://github.com/JoaquinTrinanes/nixpacks-error-repro).

It's a default laravel project (`composer create-project laravel/laravel:^10.0 example-app`) to which I added a pnpm lockfile because otherwise it wouldn't be detected as a pnpm application and would fallback to npm.

Running `nixpacks build .` is enough to trigger it (without even having a `nixpacks.toml` file).

**Comment by peaklabs-dev** [comment] 2024-11-26 13:39
This is not a Coolify problem, but a Nixpacks configuration problem.

The problem is that multiple packages are trying to install their `LINCESE` file in the same path. It can be solved by using npm instead of pnpm, or as you mentioned, by setting the priority to high so that the license file collision is resolved in favor of composer:

https://github.com/JoaquinTrinanes/nixpacks-error-repro/blob/2f1eefc3d3f04807476d7de5b4a51027d389ff74/nixpacks.toml#L3C1-L3C59

**Closed by peaklabs-dev** 2024-11-26 13:39 UTC
Labels: 🐛 Bug
