### ISSUE TITLE
[Bug]: Backup still not working

### ISSUE THREAD

**Issue by lorenzpfei** [coollabsio/coolify#3691] opened 2024-10-03 12:25 UTC
### Error Message and Logs

Firstly, I wanted to thank you for putting that much effort into cooify. It's a masterpiece and I'm recommending it over and over to my friends and collegues! <3

https://github.com/coollabsio/coolify/issues/3668
As you can see here I had two problems which are fixed at this moment. Unfortunately after updating to 350 I'm now getting the error 

> DatabaseBackupJob failed with: No query results for model [App\Models\Team] 1

Could you please have a look at the problem? Thanks!

### Steps to Reproduce

1. Go to settings
2. click on Backup now

### Coolify Version

v4.0.0-beta.350

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian GNU/Linux 12 (bookworm)

### Additional Information

happens when I check S3 (Hetzner) as well as when I uncheck it, but it seems that the error is caused a few seconds later when unchecking s3

**Comment by andrasbacsai** [comment] 2024-10-03 18:51
This will be fixed in the upcoming version. 

Now I know the root cause. :)

**Closed** 2024-10-03 18:53 UTC
Labels: 🐛 Bug, 🔍 Triage
