### ISSUE TITLE
[Bug]: Postgres Data lost after restart database

### ISSUE THREAD

**Issue by midsonlajeanty** [coollabsio/coolify#4653] opened 2024-12-23 17:53 UTC
### Error Message and Logs

No errors

### Steps to Reproduce

1. Create Posgres container ressource
2. Add database and /  or data to instance
3. Restart database

### Coolify Version

v4.0.0-beta.379

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.1 LTS

**Comment by peaklabs-dev** [comment] 2024-12-23 17:57
Duplicate of #2376

**Closed by peaklabs-dev** 2024-12-23 17:57 UTC
Labels: 🐛 Bug, 🔍 Triage
