### ISSUE TITLE
[Bug]: Scheduled actions not working

### ISSUE THREAD

**Issue by picocodes** [coollabsio/coolify#3333] opened 2024-09-06 05:18 UTC
### Description

Ever since I upgraded to version [v4.0.0-beta.325](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.325)

I'm no longer notified of Coolify updates.
Scheduled actions for my apps and services are not triggered.

### Minimal Reproduction (if possible, example repository)

I'm not sure if my update broke or what.

### Version

v4.0.0-beta.325

### Cloud?

- [ ] Yes
- [x] No

**Comment by picocodes** [comment] 2024-09-06 05:30
I tried manually updating to v4.0.0-beta.329 but this doesn't fix the issue

**Comment by ananni13** [comment] 2024-09-06 09:31
Seeing the same issues, my scheduled backups are not being triggered anymore since v4.0.0-beta.325. All configured with "0 0 * * *" cron expression.

Manual on-demand execution with "Backup Now" works.

**Comment by peaklabs-dev** [comment] 2024-09-06 10:41
Did you set a timezone in your server settings?

**Comment by picocodes** [comment] 2024-09-06 10:45
Hi @peaklabs-dev,

The timezone is set to UTC as that's the only option available.

It's always worked, issue started after I updated to v4.0.0-beta.325.

**Comment by Vahor** [comment] 2024-09-06 12:13
Just tested with `* * * * *` and a simple `echo` command, and it works for me on `v4.0.0-beta.329`

![image](https://github.com/user-attachments/assets/32da5783-c159-4c2a-b411-cc796b9f0e5b)

are you sure the scheduled actions are not working ? Maybe they are just not visible ? there is a ui bug that should be fixed with https://github.com/coollabsio/coolify/pull/3316

**Comment by peaklabs-dev** [comment] 2024-09-27 16:51
Due to inactivity, we're closing this issue. Feel free to reopen the issue if the problem is still present with the latest version.

**Closed by peaklabs-dev** 2024-09-27 16:51 UTC
Labels: 🐛 Bug
