### ISSUE TITLE
[Bug]: Scheduled backups are broken

### ISSUE THREAD

**Issue by SaizFerri** [coollabsio/coolify#3894] opened 2024-10-11 19:13 UTC
First of all, thank you for this awesome piece of software! Backups had been working flawlessly until recent upgrades.

### Error Message and Logs

```
App\Jobs\DatabaseBackupJob ..................... RUNNING
App\Jobs\DatabaseBackupJob ................ 77.92ms FAIL
```

### Steps to Reproduce

1. Open a database service like a postgres one
2. Create a weely backup
3. Hit `Backup now`

**Actual:**
A successful toast message is shown saying that the backup is queued. After a while there is no backup and upon checking the logs I see that it failed but there are no more details.
Also, after doing any version upgrade, all scheduled backups settings are gone.

**Expected:**
Backup is created successfully and backup settings stay across coolify version upgrades.

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04.4 LTS

**Comment by JakeKydd** [comment] 2024-10-17 09:35
Can verify that automated Database Backups are broken as of beta.356

MySQL backups for database instances fail,
Backups for Coolify's own database continue to work.

**Comment by shanehoban** [comment] 2024-11-05 09:30
Backups to S3 (cloudflare) started failing for me after coolify upgraded to beta.360

````
Failed to pull helper image: toomanyrequests: retry-after: 450.342µs, allowed: 44000/minute

Failed to pull helper image: toomanyrequests: retry-after: 450.342µs, allowed: 44000/minute
````

@andrasbacsai It might be worth putting the version of coolify in the backup information (pictured below), it would help with debugging as to confirm the version of coolify where the backup failed/passed.

![Image](https://github.com/user-attachments/assets/c6f23131-be8f-49d4-a973-56d1c8cec39b)

**Comment by SaizFerri** [comment] 2024-11-09 12:07
I'm not sure what I did but I had to restart the proxy and coolify was hanging on the restart, so I had to basically run the installation script again. Afterwards, my old backup schedules were still gone but after recreating them, it started working again.

**Comment by albertorizzi** [comment] 2024-11-10 03:17
Without performing any operations, tonight the backups happened correctly without any errors. I do not understand. Can this be an error that happens occasionally?

**Comment by dzusooo** [comment] 2024-11-10 08:25
Same happened to me, 2 days in a row. Never had this issue before ![Image](https://github.com/user-attachments/assets/45931287-8512-434c-9c38-19f8c67ebb51)

**Comment by albertorizzi** [comment] 2024-11-10 16:52
We are discussing this issue in this [Discord thread](https://discord.com/channels/459365938081431553/1304601135822143559). We believe the problem occurs when Coolify updates and all instances simultaneously download the helper.

**Comment by peaklabs-dev** [comment] 2024-11-14 17:07
Duplicate of #3395

**Closed by peaklabs-dev** 2024-11-14 17:07 UTC
Labels: 🐛 Bug, 🔍 Triage
