### ISSUE TITLE
[Bug]: MAC is invalid after backup restore

### ISSUE THREAD

**Issue by ivanpajon** [coollabsio/coolify#3761] opened 2024-10-07 11:33 UTC
### Error Message and Logs

I installed Coolify in a new server and I restored a backup.
I try to login but when I enter the 2FA code it shows a 500 error and I even can't access with recovery code due to same error.

![image](https://github.com/user-attachments/assets/3db33a8b-a889-4320-97e6-f7accee831c1)

EDIT:
I finally could restore a backup with 2FA enable but although UI seems to be restored internally there are something wrong. Now, if I try to enter to any configuration (S3, servers, keys...) I get the MAC invalid error. Capture below is when I try to enter to a configured S3.
![image](https://github.com/user-attachments/assets/e794990e-3e22-484d-933c-968a71620fa6)

Also, I noted that when you select in Settings > Backup the check for all databases, exported file has no extension (pg-dump-all) and it can't be used with pg_restore. If you don't select the check and not specify any database you get a dmp file as backup.

### Steps to Reproduce

1. Install Coolify in a new server
2. Restore a backup (with an account with 2FA configured)
3. Try to login

### Coolify Version

v4.0.0-beta.355

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.0.1

**Comment by ex0ns** [comment] 2024-10-22 08:29
While testing my backups I had the same issue, I think this is related to the environment variable the service is starting with.

I took the following three values out of server ( /data/coolify/source/.env) and wrote them into my new one, restarted coolify and it seems to work properly:

```
APP_ID=XXXXXX
APP_KEY=base64:CCCCC
APP_NAME=Coolify
```

I also had to add the public key of my old server to my new one, probably because Coolify's "localhost key" is stored in DB (which is restored with the backup):

```
localhost's key
The private key for the Coolify host machine (localhost).
```

So I had to add this public key to my `/root/.ssh/.authorized_keys`

**Comment by peaklabs-dev** [comment] 2024-10-23 14:24
This problem is expected when you restore Coolify to a fresh install. The problem here is your `APP_KEY`, as this environment variable is used for encryption in Laravel/ Coolify. If you restore a backup to a fresh install, Laravel/ Coolify will not work correctly because the `APP_KEY` on a new install is now a newly generated value and not the one it was before (on the old server). So Laravel/ Coolify can not decrypt your data properly.

## You have two options to fix this: 
**For both options to work, you need a backup of your old .env file or access to Coolify's `.env` file (if you do not have a backup or access to your `.env` file, neither of the two solutions will work).**
1. You can replace the new `.env` file on your server completely with the old `.env` file (not recommended).
2. My recommendation is to add your old `APP_KEY=` from your old `.env` file to the new server `.env` file as `APP_PREVIOUS_KEYS= `and then run the Coolify install script again. In your new `.env` file on the new server you should now have both a new `APP_KEY=` and your old app key from the old server as `APP_PREVIOUS_KEYS=`.

**-> To prevent this from happening in the future, always make sure you backup your `.env` file somewhere off your server. For example in a backup manager.**


--> If you do not have access or a backup of your .env file, you have only one option which is to clean install, Coolify and start from scratch.

Since this is not a bug with Coolify, I will close this issue. If you need more help, do not hesitate to contact me here or on discord.

**Closed by peaklabs-dev** 2024-10-23 14:24 UTC
Labels: 🐛 Bug
