### ISSUE TITLE
[Bug]: Setting Consistent Container Names to true still uses bad container names under the hood

### ISSUE THREAD

**Issue by dickermoshe** [coollabsio/coolify#2122] opened 2024-05-02 18:29 UTC
### Description

I've set Consistent Container Names to true so that I can run commands in a single container of my docker compose deployment.

However when running with what should be the consistent name `web-o0og8ko` it fails 
```
ScheduledTaskJob failed: No valid container was found. Is the container name correct?
```
SSHing into the machine I see that the name is actually `c8kckc8-web`

This is only affecting Scheduled jobs though, one-off tasks still use the `web-o0og8ko` name.

Btw, should paying customers be filing bugs, or contacting another way?

### Minimal Reproduction (if possible, example repository)

N/A

### Version

v4.0.0-beta.273

**Comment by andrasbacsai** [comment] 2024-05-14 10:47
> Btw, should paying customers be filing bugs, or contacting another way?

Anyone can fill bugs.

To your issue, what kind of deployment type do you use? Docker compose / dockerfile / nixpacks, etc.

**Comment by dickermoshe** [comment] 2024-05-14 12:08
Dockerfile and Docker Compose.

It has a larger impact on compose because scheduled task don't require a
name be specified for a single container

However on both the name of the Docker container when running docker ps
isn't the correct name.

**Comment by hkd987** [comment] 2024-05-28 22:18
In my case its a dockerfile.

**Comment by andrasbacsai** [comment] 2024-05-29 08:37
For docker-compose based deployments, the persistent container name should look like this:<br>`<service_stack_name>-<application_uuid>`

And in case you are not using the persistent container name:

`<service_stack_name>-<application_uuid>-<random_timestamp>`

The container name in the scheduled task selection only have the `service_stack_name` . So no matter if you enabled the persistent container name or not, the same container name will be used.

<br><br>I cannot reproduce the issue neither in `Dockerfile` and `Docker Compose` deployments. So I'm closing it now. 

If you have a step-by-step reproduction with screenshots that the container name is wrong, please reopen the issue.

**Closed by andrasbacsai** 2024-05-29 08:37 UTC
Labels: waiting for feedback
