### ISSUE TITLE
[Bug]: "Docker Compose file not found at: /docker-compose.yaml" 

### ISSUE THREAD

**Issue by komali2** [coollabsio/coolify#2962] opened 2024-07-27 05:00 UTC
### Description

I'm attempting to deploy this project: https://codeberg.org/508_dev/game-remix-guesser-backend.git using the `Docker Compose` Build Pack. 

I've confirmed the repo is publicly accessible, and I'm not getting any errors in coolify about the source being pulled. 

However, whenever I click `reload compose file`, I get the error:

```
Docker Compose file not found at: /docker-compose.yaml

Check if you used the right extension (.yaml or .yml) in the compose file name.
```

### Minimal Reproduction (if possible, example repository)

1. On a new project, select `Docker Compose` build pack
2. Set source as https://codeberg.org/508_dev/game-remix-guesser-backend.git or the github version of same: https://github.com/508-dev/game-remix-guesser-backend
3. Under `General` tab, click `Reload Compose File`
4. Observe error

### Exception or Error

Docker Compose file not found at: /docker-compose.yaml

Check if you used the right extension (.yaml or .yml) in the compose file name.

### Version

v4.0.0-beta.319

### Cloud?

- [ ] Yes
- [X] No

**Comment by 1day2die** [comment] 2024-07-30 22:03
got the same error

**Comment by irbano** [comment] 2024-08-01 10:34
I'm having the same issue, could you find a workaround ?

**Comment by irbano** [comment] 2024-08-01 10:51
Ok, the problema is caused by the git version on the server. 

See https://github.com/coollabsio/coolify/issues/2444#issuecomment-2168721249


How to fix on ubuntu:

```shell
sudo apt-get install software-properties-common -y;
sudo apt update;
sudo add-apt-repository -y ppa:git-core/ppa;
sudo apt-get update;
sudo apt-get install git -y;
```

**Comment by JohnFajardo** [comment] 2024-08-12 02:25
Solution not working on Arch. I'm on git v2.46.0 and the issue is still present.

**Comment by ayntk-ai** [comment] 2024-08-13 09:37
I am investigating this as I have the same problem. But it is not consistently reproducible, so a fix will be hard.

**Comment by ayntk-ai** [comment] 2024-08-13 10:27
Found it and fixing it currently will release a PR shortly

**Comment by peaklabs-dev** [comment] 2024-08-18 22:35
@komali2 I did a very deep investigation and I think this bug is already fixed.

**Could you please retest on the latest version of coolify, and make sure you have the right extension yaml or yml?**
and if you are a developer see my comment here https://github.com/coollabsio/coolify/pull/3075#issue-2464160205

**Comment by komali2** [comment] 2024-08-19 11:47
> @komali2 I did a very deep investigation and I think this bug is already fixed.
> 
> **Could you please retest on the latest version of coolify, and make sure you have the right extension yaml or yml?** and if you are a developer see my comment here [#3075 (comment)](https://github.com/coollabsio/coolify/pull/3075#issue-2464160205)

Happy to double check that it's updated, however your included script "resets the dev environment" - can you clarify what this means? We have many live things deployed on coolify and redeploying everything will be tedious, I'll need to create a mirror instance and point a lot of URLs to another server, etc. I'm ready to do that of course as a routine backup strategy but I don't want to do it unnecessarily.

**Comment by peaklabs-dev** [comment] 2024-08-19 12:43
**Please make a proper full server backup to be safe.**

@komali2 The following command `docker exec -it coolify php artisan migrate:fresh --seed` should only be run if you are a developer and have a local coolify install and are contributing to the project (In production this would not be a good idea as it essentially factory resets coolify and populates it with test data). For your case DO NOT run the command in production. 
**For you:**
1. Update coolify
2. Test again --> You should also test with coolify examples: https://github.com/coollabsio/coolify-examples/ --> the Base Directory is: `/docker-compose-test` and the Docker Compose Location is: `/docker-compose.yaml`. (make sure to use the main branch)

**Comment by peaklabs-dev** [comment] 2024-09-12 16:50
This should be fixed in the latest coolify release. Please re-open the issue if you can reproduce the problem consistently.

**Closed by peaklabs-dev** 2024-09-12 16:50 UTC
Labels: 💤 Waiting for feedback

**Comment by DavidNgugi** [comment] 2024-09-14 16:33
I'm on the latest release and I still get this error

**Comment by peaklabs-dev** [comment] 2024-09-14 20:32
@DavidNgugi Could you please open a new issue with detailed reproduction steps and an example repo as we can not reproduce this.

**Comment by DavidNgugi** [comment] 2024-09-16 07:56
@peaklabs-dev Issue resolved. Seems it's a key mismatch issue. Weird error though
