### ISSUE TITLE
[Bug]: Terminal function doesn't seem to use the Websocket domain

### ISSUE THREAD

**Issue by davidpp** [coollabsio/coolify#3649] opened 2024-10-01 02:53 UTC
### Error Message and Logs

I'm not able to use the Terminal feature.

Looking at my console, I'm seeing an attempt to connect to my "non websocket" url:

![CleanShot 2024-09-30 at 22 50 41@2x](https://github.com/user-attachments/assets/43a473eb-4e67-4c96-b9d8-e6db70350ac9)

Where other features correctly use my websocket domain:

![CleanShot 2024-09-30 at 22 51 43@2x](https://github.com/user-attachments/assets/aaf7f4ab-fe66-494c-b3a9-7ee7d72b98ac)

### Steps to Reproduce

1. Have a separate domain configured for WS connection
2. Try to open a terminal session on a service

### Coolify Version

v4.0.0-beta.347

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by LEstradioto** [comment] 2024-10-01 04:55
How did you setup a different WS domain ?

**Comment by djsisson** [comment] 2024-10-01 07:57
Traefik will send wss to the real-time container as long as you are accessing via the instance domain.

There is no need to change anything here

**Comment by davidpp** [comment] 2024-10-04 21:35
Looking back at my note, the ws. subdomain is the pusher server.

The reason I had to configure a separate domain is because of Cloudflare Access since pusher is running on another port.

Knowing that this particular traffic is instead going through Traefik, it make sense that it's using the main domain then.

The issue is probably on the Cloudflare tunnel/access side then, I'll need to figure out why the error is happening

**Comment by djsisson** [comment] 2024-10-05 09:58
@davidpp if youre using a tunnel, and the coolify domain isnt covered by a wildcard entry, then you just set the coolify suibdomain to be localhost 80, traefik will then route all traffic (http and wss) to the correct containers

**Comment by CallMeSlinky** [comment] 2024-10-05 17:06
@davidpp I'm currently facing the same issue, please update if you find a resolution, thanks. 👍

**Comment by CallMeSlinky** [comment] 2024-10-05 17:22
@davidpp I figured it out. My coolify is based at https://coolify.example.com I set this in Cloudflare tunnels for the terminal

![image](https://github.com/user-attachments/assets/f8a2a6bd-5663-49a4-b81c-e8839e545d76)

**Comment by VipinGoyal** [comment] 2024-10-06 09:40
I tried this @CallMeSlinky , but I'm still getting same problem as per OP shared screenshot.

**Comment by djsisson** [comment] 2024-10-06 09:43
if youre still running traefik, then from the above example, all you need to do is set coolify.example.com to be localhost 80

**Comment by VipinGoyal** [comment] 2024-10-06 09:47
I just refreshed, what I found is that original error as per OP is gone after making changes as suggested by @CallMeSlinky , but terminal is not working.
@djsisson Yes Im using default proxy coming, no change in that, Im facing weird issue, after changing port number from 8000 to 80, Im getting this error in browser i.e. 

coolify.example.com redirected you too many times.
[Try deleting your cookies](https://support.google.com/chrome?p=rl_error&hl=en-GB).
ERR_TOO_MANY_REDIRECTS

Am I missing something ?

**Comment by djsisson** [comment] 2024-10-06 09:48
you need to set it as http in instancedomain in coolify

**Comment by VipinGoyal** [comment] 2024-10-06 09:55
![image](https://github.com/user-attachments/assets/e58540bd-70c6-4d98-8259-f56684e20253)

Do you mean value of **IP address / Domain** ins erver settings ?  Currently its set as **host.docker.internal**, since Im not using wildcard domain. 
When I tried updating value of IP address / Domain to coolify.example.com, I got an alert like this, so before doing this thought of checking with you just to make sure that its not going to break existing setup 

![image](https://github.com/user-attachments/assets/375be5f0-428d-4de4-8c15-f2a8747bad4b)

**Comment by djsisson** [comment] 2024-10-06 09:56
no on settings page - > instance domain

**Comment by VipinGoyal** [comment] 2024-10-06 10:02
Wao, it worked  thanks a lot :) 🙏 
So, coolify.example.com is mapped with localhost:80 instead of 8000, is it okay, If I remove other mappings in cloudflare ( public hostname ) like 6001 for realtime and 6002 for terminal/ws path, Im about to delete those, but just confirming with you once.

**Comment by djsisson** [comment] 2024-10-06 10:05
if you are running a proxy like traefik,

then in tunnels you only need to point to http localhost : 80 and the proxy will take care of it
or https localhost  : 443 if you have setup certificates and require https in your containers

**Comment by VipinGoyal** [comment] 2024-10-06 10:07
Sure, thanks for confirmation, its really helpful. 🙏

**Comment by CallMeSlinky** [comment] 2024-10-06 11:38
> Wao, it worked thanks a lot :) 🙏 So, coolify.example.com is mapped with localhost:80 instead of 8000, is it okay, If I remove other mappings in cloudflare ( public hostname ) like 6001 for realtime and 6002 for terminal/ws path, Im about to delete those, but just confirming with you once.

Nice, this worked for me too, a lot more simple. I was receiving ERR_TOO_MANY_REDIRECTS beforehand, but I believe it's because my instance domain was set to https. 👍

**Comment by peaklabs-dev** [comment] 2024-11-20 22:33
I believe this has been resolved and is not a bug but rather a configuration issue, so I will close this.

**Closed by peaklabs-dev** 2024-11-20 22:33 UTC
Labels: 🐛 Bug, 🔍 Triage
