### ISSUE TITLE
[Bug]: "coolify-proxy" container does not exist, so accessing the instance via the domain is impossible

### ISSUE THREAD

**Issue by realslimsutton** [coollabsio/coolify#3279] opened 2024-09-01 01:37 UTC
### Description

I've noticed my "coolify-proxy" container is not among my list of docker containers.

This is the output I get when running `docker ps -a`:
<img width="1700" alt="image" src="https://github.com/user-attachments/assets/1c1a1c76-f3a2-4683-97f5-14d72afc17e3">

Running both the `install.sh` and `upgrade.sh` scripts do not re-create this proxy, and when accessing the domain I set in the  "Instance's Domain" setting, I get a "Web server is down - Error 521" via Cloudflare. I can access the instance via the IP.
The domain hasn't changed, and both the A record in the Cloudflare DNS, and the IP of the server hasn't changed.

Additionally, none of the domain's I set for all the services that are running are working either. I get the same Cloudflare error, and they also were previously working.

Output after running `install.sh`:
<img width="514" alt="image" src="https://github.com/user-attachments/assets/6e2b377c-bd26-490d-8446-d06503c98665">

Output after running `upgrade.sh`:
<img width="723" alt="image" src="https://github.com/user-attachments/assets/7b1c1daf-adf6-4d8d-a4b7-031a6b70b3a8">

### Minimal Reproduction (if possible, example repository)

Unsure how to reproduce, this randomly occurred after a server restart. Creating a fresh instance on my local machine does not cause this issue.

### Version

4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by realslimsutton** [comment] 2024-09-01 01:57
Upon further investigation, this actually appears to be related to #3107.

Port 80 is being used by the `coolify` container, which is causing coolify to be unable to start the proxy.

**Comment by realslimsutton** [comment] 2024-09-12 03:13
> Facing same issue here.

Unfortunately, I wasn’t able to figure out what caused the containers to get so messed up. I ended up spending more time on the investigation than I would have just deleting the coolify containers and re-deploying them fresh - and unfortunately that’s not time I currently have spare.

Definitely not an ideal workaround, but in my case it made more sense time-wise to start coolify from fresh and redeploying my services rather than manually fixing the containers.

**Comment by nerijunior** [comment] 2024-09-12 03:18
Don't know about the root cause but I tap "Switch Proxy" selected Traefik, saved and it fixed.

**Comment by jodyhoonstarr** [comment] 2024-09-18 02:50
> Don't know about the root cause but I tap "Switch Proxy" selected Traefik, saved and it fixed.

Following this, in the coolify ui switching to both traefik & caddy failed with an error message "caddy-proxy already exists", then back to the *Custom (None)* proxy fixed the issue.

**Comment by peaklabs-dev** [comment] 2024-09-24 17:25
The installer or updated script does not install/start the proxy because there are different proxy types handled in the UI. You most likely ran into a rare issue where the proxy crashed and then the cleanup job removed the proxy so it was never restarted so the proxy was gone, I will add a fix for this.

**Closed** 2024-09-28 09:14 UTC
