### ISSUE TITLE
[Bug]: Container backups are either non-existent or not scheduling

### ISSUE THREAD

**Issue by graphiostudio** [coollabsio/coolify#3681] opened 2024-10-03 07:36 UTC
### Error Message and Logs

This issue has been asked numerous times on Discord channel but none of them got proper replies and fixes. There are similar open issues as well. 
-Some container databases doesn't come with a backup option when you go into their settings.
-The ones that have a backup option in their settings do not keep the schedules saved. It DOES work when you set and hit backup now, but a quick refresh or server restart deletes them (not the backup files but the scheduling).
- Hitting the download button doesn't download the backup on any part of the whole system.

### Steps to Reproduce

1. Install Mixpost and observe there's no backup option on MySQL database
2. Install Plane (for example) and if there's a backup option, schedule one.
3. Click backup now, and observe it works.
4. Refresh the page or restart the server, schedule is empty.
5. Hit download and observe that is not downloading

### Coolify Version

v4.0.0-beta.349

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22

### Additional Information

Schedule set, backup working and uploaded to S3:
<img width="1045" alt="image" src="https://github.com/user-attachments/assets/ee2ded93-3db4-4881-906d-f99cf4cb2044">

A quick refresh, or server restart, and that schedule is gone. This applies to all container backups, postgres, DB, and MySQL on multiple servers.
<img width="1047" alt="image" src="https://github.com/user-attachments/assets/9e25a6d2-5c6d-496f-837d-9efbfb3d3c40">

And some templates like Mixpost for instance, don't even have the backup option on the container, this also applies to the most recent template on Directus, when I use an old version of the Directus template, backup appears but still, doesn't schedule.
<img width="1050" alt="image" src="https://github.com/user-attachments/assets/9e8279fe-08fa-4760-b5cb-067132916131">

**Comment by andrasbacsai** [comment] 2024-10-03 14:54
Yes, it is because Coolify detects that if the service is a database or not by the image name. `mysql-server` is not in the list. I will update the image list.

(If you know a better way to do this, let me know)

**Comment by graphiostudio** [comment] 2024-10-08 07:30
Hey @andrasbacsai, thanks for the reply. That 'mysql-server' was a default by Mixpost template. 
<img width="892" alt="image" src="https://github.com/user-attachments/assets/fbdd41d7-51ff-43b9-9cd0-adc4bcb4ae00">
I guess, I need to double-check the template compose before deploying. However, the backups disappearing issue still persists. On 355, most databases now have a backups link but setting one doesn't really do anything, they will disappear like the example above. Also, keep getting these discord messages like in this issue: https://github.com/coollabsio/coolify/issues/3395

**Comment by peaklabs-dev** [comment] 2024-11-14 17:30
Not all DBs have backup options yet. It is planned to implement a full backup manager in the future. I am not able to reproduce the backup disappearing problems, so I will close this issue. If this comes up again and backups start disappearing, please open a new issue with more detailed reproduction steps.

**Closed by peaklabs-dev** 2024-11-14 17:30 UTC
Labels: 🐛 Bug, 🔍 Triage
