### ISSUE TITLE
PullHelperImageJob

### ISSUE THREAD

**Issue by yashkolambekar** [coollabsio/coolify#3809] opened 2024-10-09 10:03 UTC
### Error Message and Logs

![Screenshot_20241009_153024](https://github.com/user-attachments/assets/17ba64a4-df9c-44c8-a54e-cf0f08a00bcc)

### Steps to Reproduce

Not sure

### Coolify Version

V4

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22

**Comment by peaklabs-dev** [comment] 2024-10-09 10:07
This issue appears to be a duplicate of #3395. Please move to that issue for updates and discussions.

**Closed by peaklabs-dev** 2024-10-09 10:07 UTC
Labels: 🐛 Bug, 🔍 Triage
