### ISSUE TITLE
[Bug]: Paste .env file not working trim

### ISSUE THREAD

**Issue by dondonjang** [coollabsio/coolify#542] opened 2022-08-17 00:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I pasted `Paste .env file`

It used to be "trim" normally,
"Trim" doesn't work after this upgrade
An error is occurring when the service is running.

### Steps To Reproduce

I pasted `Paste .env file`

### Version

v3.4.0

**Comment by andrasbacsai** [comment] 2022-08-17 09:36
Can you please show me an example `.env` file (of course without real values)?

I cannot reproduce it.

**Comment by dondonjang** [comment] 2022-08-17 09:52
example 
 i am pasted under db server info 
 
DATABASE_HOST = 1111.sldb.222.net
DATABASE_USERNAME = root
DATABASE_PASSWORD = 2222
DATABASE_NAME = 333

server not start after deploy

**Comment by dondonjang** [comment] 2022-08-17 09:55
2022-08-17T09:53:27.705246042Z     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
2022-08-17T09:53:27.705241393Z Error: getaddrinfo ENOTFOUND 1111.sldb.222.net 
2022-08-17T09:53:27.705173958Z [Nest] 21  - 08/17/2022, 6:53:27 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...

my local is working
but if I add host name after add blank 
it is not working

**Comment by andrasbacsai** [comment] 2022-08-17 10:05
Is that DB hosted by Coolify? If yes, is it set to public or are you using it internally (without setting it to public)?

Pasting the exact `.env` to `Paste .env file` works, so the problem is different.

**Comment by dondonjang** [comment] 2022-08-17 10:23
I use `Paste .env file` 
this DB host is another service

**Comment by dondonjang** [comment] 2022-08-17 10:25
It worked fine before the version update.
After updating this version, an error occurred when deploying,
So I pasted it again, and the error is occurring.
There is a space after the host name

**Comment by dondonjang** [comment] 2022-08-17 10:27
An error occurred during distribution because some values had "" in the previously registered env file.

```
[00:28:44.235] Error: Command failed: DOCKER_BUILDKIT=1 DOCKER_HOST="unix:///var/run/docker.sock" docker compose --project-directory /tmp/build-sources/dondonjang/pantaoapi/cl6wvktjc00090oppdsv14sk9 up -d
unexpected character "'" in variable name near "espacio' '\n
```

**Comment by andrasbacsai** [comment] 2022-08-17 11:33
Ah, I found the problem (again). It was introduced by [this](https://github.com/docker/compose/issues/9704). I reverted docker compose version to 2.6.1 till it is fixed.

Will be fixed in the next version (releasing soon).

**Closed** 2022-08-17 11:43 UTC
