### ISSUE TITLE
[Bug]: Can't reach Minio S3 console after deploy

### ISSUE THREAD

**Issue by aybasaran** [coollabsio/coolify#2124] opened 2024-05-03 01:51 UTC
### Description

Hello Everyone, 
I've been facing problems with MinioS3. I can't react the minio console after deploy.

### Version

v4.0.0-beta.271

**Comment by nimaa77** [comment] 2024-05-08 11:19
how did you managed to fix this issue?

**Comment by aybasaran** [comment] 2024-05-14 07:46
@nimaa77 i found a solution. I change my proxy server into Caddy and it worked

**Comment by nunocasteleira** [comment] 2024-05-16 18:42
this problem still persists. I tried to debug the docker compose by myself, but with no luck. Traefik rule doesn't appear on dashboard, so it's probably related to that.

**Comment by aybasaran** [comment] 2024-05-16 22:29
> this problem still persists. I tried to debug the docker compose by myself, but with no luck. Traefik rule doesn't appear on dashboard, so it's probably related to that.

Did you try using Caddy as a proxy server? That's an easy process.
![image](https://github.com/coollabsio/coolify/assets/23173783/f92adebd-c824-49aa-b64a-331a95932994)

**Comment by nunocasteleira** [comment] 2024-05-16 22:39
> > this problem still persists. I tried to debug the docker compose by myself, but with no luck. Traefik rule doesn't appear on dashboard, so it's probably related to that.
> 
> 
> 
> Did you try using Caddy as a proxy server? That's an easy process.
> 
> ![image](https://github.com/coollabsio/coolify/assets/23173783/f92adebd-c824-49aa-b64a-331a95932994)
> 
> 

Yes, but I prefer to keep traefik. Nonetheless, I'll take a look on using Caddy.

**Comment by nicnocquee** [comment] 2024-06-11 13:17
I'm using Caddy but still cannot login. Any other ideas?

**Comment by aybasaran** [comment] 2024-06-11 13:21
> I'm using Caddy but still cannot login. Any other ideas?

Did you add DNS records?

**Comment by nicnocquee** [comment] 2024-06-11 13:53
i don't use cloudflare, in namecheap like this:

![image](https://github.com/coollabsio/coolify/assets/311343/b125855c-bdb1-45ef-8a17-ecbaf10d31f9)

and in coolify

<img width="739" alt="Screenshot 2024-06-11 at 15 51 28" src="https://github.com/coollabsio/coolify/assets/311343/93a463f5-582e-4473-8781-f16d73ad7200">

**Comment by aybasaran** [comment] 2024-06-11 14:25
> i don't use cloudflare, in namecheap like this:
> 
> ![image](https://private-user-images.githubusercontent.com/311343/338610085-b125855c-bdb1-45ef-8a17-ecbaf10d31f9.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTU5NjAsIm5iZiI6MTcxODExNTY2MCwicGF0aCI6Ii8zMTEzNDMvMzM4NjEwMDg1LWIxMjU4NTVjLWJkYjEtNDVlZi04YTE3LWVjYmFmMTBkMzFmOS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMTQyMTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU5MGI2MTIxNjgxYzdlYmQzNzdhZjg5MWU4ZjBmZjRlMmIwZWQ3OGEwNjhkYTMyNzNiN2NlY2E1YzNmNDg1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Hox5oVmzhX6laCX9f6ovarW-U6MvfZHh2uPuEWIeREA)
> 
> and in coolify
> 
> <img alt="Screenshot 2024-06-11 at 15 51 28" width="739" src="https://private-user-images.githubusercontent.com/311343/338611096-93a463f5-582e-4473-8781-f16d73ad7200.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTU5NjAsIm5iZiI6MTcxODExNTY2MCwicGF0aCI6Ii8zMTEzNDMvMzM4NjExMDk2LTkzYTQ2M2Y1LTU4MmUtNDQ3My04NzgxLWYxNmQ3M2FkNzIwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxNDIxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDhmM2NkZDYzY2EyYjZhMDI3OWNhYTRmN2FlY2U0MTRmZGM2MjY3ZGY5NmRmMzRlNGMwOWVjZmRhYTc4OWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tZomrP4di9P3SsmtdDpDMN38GnGsJ1kwNi3dtkg55ew">
> version v4.0.0-beta.294 btw

Can you try uploads.example.com and minio-console.example.com instead of *.minio.example.com. (aliases up to you, you can try what ever you want but not double sub domain)

**Comment by nicnocquee** [comment] 2024-06-11 14:48
Still doesn't work. I noticed when I visited the console URL, it always took a while to redirect to login. When I looked at the network log, there was a timeout calling https://minio.my-domain/api/v1/session with error:

```
{
    "detailedMessage": "Get \"https://upload-minio.my-domain/minio/admin/v3/accountinfo\": dial tcp <ip-address>:443: i/o timeout",
    "message": "invalid session"
}
```

i wonder if it's related.

some more info if needed:

- the server running minio is not the same with coolify instance.
- i have entered the wildcard domain in the server -> general setting page
- i don't change anything in the caddy configuration file.

**Comment by nicnocquee** [comment] 2024-06-11 15:05
So i tried to add a new server, then installed and deployed minio, without any change, no custom domain. It worked I could login but no https.

Then I set my custom domain with https in the minio setting. This caused the "Invalid Login" error.

Then I changed the proxy to caddy. Now it worked!

So I guess because in my previous server I have the wildcard domain set?

**Comment by aybasaran** [comment] 2024-06-11 15:18
> So i tried to add a new server, then installed and deployed minio, without any change, no custom domain. It worked I could login but no https.
> 
> Then I set my custom domain with https in the minio setting. This caused the "Invalid Login" error.
> 
> Then I changed the proxy to caddy. Now it worked!
> 
> So I guess because in my previous server I have the wildcard domain set? Any ideas how to fix without removing the wildcard domain?

Double subdomain is something new for coolify i guess. Just use single subdomain with the wildcard. I always use this.

**Comment by nicnocquee** [comment] 2024-06-11 15:25
I think the difference between your setup and mine is that I have two servers, one for coolify instance and another one where I tried to deploy minio. 

The coolify instance has https://coolify.example.com domain with Traefik proxy. The other server where I installed minio has https://magic.coolify.example.com wildcard with Caddy proxy.

When I added the third server without setting the wildcard domain (but with caddy proxy), minio can be accessed. 

Honestly I'm not familiar with Traefik and Caddy but that's my finding.

**Comment by nicnocquee** [comment] 2024-06-12 00:37
After tinkering for hours and a good quick nap, I finally figured out the problem: I have ufw enabled in my server!

Disabling the ufw fixed it. But I want to keep the ufw enabled. Allowing incoming to port 9000 and 9001 didn't work. What worked was adding rule to allow all incoming traffic from the ip address of the minio container:

1. Get the ip of the minio container: `sudo docker network inspect <minio service uuid>`. You can get the uuid from the url in the coolify dashboard when you're in the minio service page, like `https://coolifydomain/project/<project-id>/production/service/<the-minio-id-we-want>#webhooks`
2. Find the "IPv4Address" of the container in the output of the command above.
3. then run `sudo ufw allow from <the ipv4 address from step 2>`
4. `sudo ufw reload`

**Comment by exoer** [comment] 2024-06-28 07:37
Same here. I have made multiple attempts with `minio`. The containers are able to start, and they run in an **unhealthy state**. When going to the console URL, I always get `404`.

**Comment by tolstenko** [comment] 2024-06-28 14:23
I am facing the same difficulties here, too: an unhealthy state of Minio. If I change the proxy from Traefik to Caddy, Minio works, but one of our services, Ghost, stops working. Well, I would rather stay with Traefik for now.

**Comment by tolstenko** [comment] 2024-06-28 16:05
Just to add the screenshots of the steps to reproduce on the latest version 306 and Traefik. It works fine with Caddy, but if i use Caddy, Ghost stops working.
<details><summary>Details</summary>
<p>
<img width="1510" alt="0" src="https://github.com/coollabsio/coolify/assets/2386417/93fe6028-050d-40e9-aff1-551a32ad2b84">
<img width="1510" alt="1" src="https://github.com/coollabsio/coolify/assets/2386417/b266eab7-2756-470c-aa6d-a65fdcb3e4fe">
<img width="1510" alt="2" src="https://github.com/coollabsio/coolify/assets/2386417/5b0fdfa3-b106-402c-83c2-9cce3b6a94f0">
<img width="1510" alt="3" src="https://github.com/coollabsio/coolify/assets/2386417/d9b3b334-81d7-455b-b125-246ada9a372e">
<img width="1510" alt="4" src="https://github.com/coollabsio/coolify/assets/2386417/27803df5-f6b8-4af7-b730-97b55e3c72a2">
<img width="1510" alt="5" src="https://github.com/coollabsio/coolify/assets/2386417/b2774fc5-5a16-4878-afe9-b1227fb240cb">
</p>
</details>

**Comment by exoer** [comment] 2024-06-28 17:15
@tolstenko So it looks like the problem is related to the proxy 🧐

**Comment by mateusfmello** [comment] 2024-07-15 13:14
This problem has already been resolved in PR https://github.com/coollabsio/coolify/pull/2837

**Closed** 2024-07-24 14:02 UTC
